#
# Macro file for "TestEm3.cc" 
#
# Al-Au-Al  1 layer;
#
# G.L.Lockwood et al. SAND79-0414 (1980)
#
/control/verbose 2
/run/verbose 2
#
/testem/phys/addPhysics  local
#
/testem/det/setNbOfLayers 1
/testem/det/setNbOfAbsor  3
/testem/det/setAbsor 1 Aluminium 170 um
/testem/det/setAbsor 2 Gold 23 um
/testem/det/setAbsor 3 Aluminium 850 um
/testem/det/setSizeYZ 1050 um
#
/run/setCut 1 um
#
##/run/initialize
