Geant4 VMC: TG4OpGeometryManager Class Reference
TG4OpGeometryManager Class Reference
geometry
Geant4 implementation of the TVirtualMC interface methods for definition of material properties for optical processes.
#include <TG4OpGeometryManager.h>
Public Member Functions
TG4OpGeometryManager ()
virtual ~TG4OpGeometryManager ()
virtual void SetCerenkov (Int_t itmed, Int_t npckov, Float_t *ppckov, Float_t *absco, Float_t *effic, Float_t *rindex)
virtual void SetCerenkov (Int_t itmed, Int_t npckov, Double_t *ppckov, Double_t *absco, Double_t *effic, Double_t *rindex)
virtual void DefineOpSurface (const char *name, EMCOpSurfaceModel model, EMCOpSurfaceType surfaceType, EMCOpSurfaceFinish surfaceFinish, Double_t sigmaAlpha)
virtual void SetBorderSurface (const char *name, const char *vol1Name, int vol1CopyNo, const char *vol2Name, int vol2CopyNo, const char *opSurfaceName)
virtual void SetSkinSurface (const char *name, const char *volName, const char *opSurfaceName)
virtual void SetMaterialProperty (Int_t itmed, const char *propertyName, Int_t np, Double_t *pp, Double_t *values)
virtual void SetMaterialProperty (Int_t itmed, const char *propertyName, Double_t value)
virtual void SetMaterialProperty (const char *surfaceName, const char *propertyName, Int_t np, Double_t *pp, Double_t *values)
virtual void Gfmate (Int_t imat, char *name, Float_t &a, Float_t &z, Float_t &dens, Float_t &radl, Float_t &absl, Float_t *ubuf, Int_t &nbuf)
virtual void Gfmate (Int_t imat, char *name, Double_t &a, Double_t &z, Double_t &dens, Double_t &radl, Double_t &absl, Double_t *ubuf, Int_t &nbuf)
virtual Bool_t GetMaterial (Int_t imat, TString &name, Double_t &a, Double_t &z, Double_t &density, Double_t &radl, Double_t &inter, TArrayD &par)
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Private Member Functions
TG4OpGeometryManager (const TG4OpGeometryManager &right)
Not implemented.
TG4OpGeometryManager & operator= (const TG4OpGeometryManager &right)
Not implemented.
Double_t AddUnit (const G4String &propertyName, Double_t value) const
Private Attributes
TG4GeometryServices * fGeometryServices
geometry services
TG4OpSurfaceMap * fOpSurfaceMap
map of optical surfaces names to their objects
Detailed Description
Geant4 implementation of the TVirtualMC interface methods for definition of material properties for optical processes.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 39 of file TG4OpGeometryManager.h.
Constructor & Destructor Documentation
TG4OpGeometryManager::TG4OpGeometryManager ()
Default constructor
Definition at line 54 of file TG4OpGeometryManager.cxx.
TG4OpGeometryManager::~TG4OpGeometryManager () virtual
Destructor
Definition at line 68 of file TG4OpGeometryManager.cxx.
TG4OpGeometryManager::TG4OpGeometryManager (const TG4OpGeometryManager & right) private
Not implemented.
Member Function Documentation
void TG4OpGeometryManager::SetCerenkov (Int_t itmed, Int_t npckov, Float_t * ppckov, Float_t * absco, Float_t * effic, Float_t * rindex) virtual
Geant3 desription:
Stores the tables for UV photon tracking in medium ITMED Please note that it is the user's responsability to provide all the coefficients:
ITMED Tracking medium number
NPCKOV Number of bins of each table
PPCKOV Value of photon momentum (in GeV)
ABSCO Absorbtion coefficients dielectric: absorbtion length in cm metals : absorbtion fraction (0<=x<=1)
EFFIC Detection efficiency for UV photons
RINDEX Refraction index (if=0 metal)
Definition at line 143 of file TG4OpGeometryManager.cxx.
Referenced by TGeant4::SetCerenkov().
void TG4OpGeometryManager::SetCerenkov (Int_t itmed, Int_t npckov, Double_t * ppckov, Double_t * absco, Double_t * effic, Double_t * rindex) virtual
Geant3 desription:
Stores the tables for UV photon tracking in medium ITMED Please note that it is the user's responsability to provide all the coefficients:
ITMED Tracking medium number
NPCKOV Number of bins of each table
PPCKOV Value of photon momentum (in GeV)
ABSCO Absorbtion coefficients dielectric: absorbtion length in cm metals : absorbtion fraction (0<=x<=1)
EFFIC Detection efficiency for UV photons
RINDEX Refraction index (if=0 metal)
Definition at line 178 of file TG4OpGeometryManager.cxx.
void TG4OpGeometryManager::DefineOpSurface (const char * name, EMCOpSurfaceModel model, EMCOpSurfaceType surfaceType, EMCOpSurfaceFinish surfaceFinish, Double_t sigmaAlpha) virtual
Define the optical surface
Definition at line 256 of file TG4OpGeometryManager.cxx.
Referenced by TGeant4::DefineOpSurface().
void TG4OpGeometryManager::SetBorderSurface (const char * name, const char * vol1Name, int vol1CopyNo, const char * vol2Name, int vol2CopyNo, const char * opSurfaceName) virtual
Define the optical border surface
Definition at line 273 of file TG4OpGeometryManager.cxx.
Referenced by TGeant4::SetBorderSurface().
void TG4OpGeometryManager::SetSkinSurface (const char * name, const char * volName, const char * opSurfaceName) virtual
Define the optical skin surface
Definition at line 310 of file TG4OpGeometryManager.cxx.
Referenced by TGeant4::SetSkinSurface().
void TG4OpGeometryManager::SetMaterialProperty (Int_t itmed, const char * propertyName, Int_t np, Double_t * pp, Double_t * values) virtual
Set the material property specified by propertyName to the tracking medium
Definition at line 338 of file TG4OpGeometryManager.cxx.
Referenced by TGeant4::SetMaterialProperty().
void TG4OpGeometryManager::SetMaterialProperty (Int_t itmed, const char * propertyName, Double_t value) virtual
Set the material property specified by propertyName to the tracking medium
Definition at line 383 of file TG4OpGeometryManager.cxx.
void TG4OpGeometryManager::SetMaterialProperty (const char * surfaceName, const char * propertyName, Int_t np, Double_t * pp, Double_t * values) virtual
Set the material property specified by propertyName to the optical surface
Definition at line 427 of file TG4OpGeometryManager.cxx.
void TG4OpGeometryManager::Gfmate (Int_t imat, char * name, Float_t & a, Float_t & z, Float_t & dens, Float_t & radl, Float_t & absl, Float_t * ubuf, Int_t & nbuf) virtual
Return parameters for material specified by material number imat
Definition at line 470 of file TG4OpGeometryManager.cxx.
Referenced by TGeant4::Gfmate().
void TG4OpGeometryManager::Gfmate (Int_t imat, char * name, Double_t & a, Double_t & z, Double_t & dens, Double_t & radl, Double_t & absl, Double_t * ubuf, Int_t & nbuf) virtual
Return parameters for material specified by material number imat
Definition at line 489 of file TG4OpGeometryManager.cxx.
Bool_t TG4OpGeometryManager::GetMaterial (Int_t imat, TString & name, Double_t & a, Double_t & z, Double_t & density, Double_t & radl, Double_t & inter, TArrayD & par) virtual
Return parameters for material specified by material number imat (new function)
Definition at line 525 of file TG4OpGeometryManager.cxx.
Referenced by TGeant4::GetMaterial().
TG4OpGeometryManager& TG4OpGeometryManager::operator= (const TG4OpGeometryManager & right) private
Not implemented.
Double_t TG4OpGeometryManager::AddUnit (const G4String & propertyName, Double_t value) const private
Add unit to a given property value and print a warning if the property is not known to the VMC interface
Definition at line 78 of file TG4OpGeometryManager.cxx.
Referenced by SetMaterialProperty().
Member Data Documentation
TG4GeometryServices* TG4OpGeometryManager::fGeometryServices private
geometry services
Definition at line 91 of file TG4OpGeometryManager.h.
Referenced by DefineOpSurface(), GetMaterial(), Gfmate(), SetBorderSurface(), SetCerenkov(), SetMaterialProperty(), SetSkinSurface(), and TG4OpGeometryManager().
TG4OpSurfaceMap* TG4OpGeometryManager::fOpSurfaceMap private
map of optical surfaces names to their objects
Definition at line 94 of file TG4OpGeometryManager.h.
Referenced by SetBorderSurface(), SetMaterialProperty(), SetSkinSurface(), and TG4OpGeometryManager().
The documentation for this class was generated from the following files:
source/geometry/include/TG4OpGeometryManager.h
source/geometry/src/TG4OpGeometryManager.cxx