Geant4 VMC: TG4TrackInformation Class Reference
TG4TrackInformation Class Reference
physics
Defines additional track information.
#include <TG4TrackInformation.h>
Public Member Functions
TG4TrackInformation ()
TG4TrackInformation (G4int trackParticleID)
virtual ~TG4TrackInformation ()
void * operator new (size_t)
Override new operator for G4Allocator.
void operator delete (void *trackInformation)
Override delete operator for G4Allocator.
virtual void Print () const
void SetTrackParticleID (G4int trackParticleID)
void SetParentParticleID (G4int parentParticleID)
void SetPDGLifetime (G4double pdgLifetime)
void SetPDGEncoding (G4int pdgEncoding)
void SetIsUserTrack (G4bool isUserTrack)
void SetStop (G4bool stop)
G4int GetTrackParticleID () const
G4int GetParentParticleID () const
G4double GetPDGLifetime () const
G4int GetPDGEncoding () const
G4bool IsUserTrack () const
G4bool IsStop () const
Private Attributes
G4int fTrackParticleID
the index of track particle in VMC stack
G4int fParentParticleID
the index of parent track in VMC stack
G4double fPDGLifetime
the original particle PDG lifetime
G4double fPDGEncoding
the particle PDG encoding
G4bool fIsUserTrack
true if defined by user and not primary track
G4bool fStop
true if track should be stopped
Detailed Description
Defines additional track information.
Author
I. Hrivnacova; IPN Orsay
Definition at line 29 of file TG4TrackInformation.h.
Constructor & Destructor Documentation
TG4TrackInformation::TG4TrackInformation ()
Default constructor
Definition at line 21 of file TG4TrackInformation.cxx.
TG4TrackInformation::TG4TrackInformation (G4int trackParticleID)
Standard constructor
Definition at line 34 of file TG4TrackInformation.cxx.
TG4TrackInformation::~TG4TrackInformation () virtual
Destructor
Definition at line 57 of file TG4TrackInformation.cxx.
Member Function Documentation
void* TG4TrackInformation::operator new (size_t) inline
Override new operator for G4Allocator.
void TG4TrackInformation::operator delete (void * trackInformation) inline
Override delete operator for G4Allocator.
void TG4TrackInformation::Print () const virtual
Print track information.
Definition at line 67 of file TG4TrackInformation.cxx.
void TG4TrackInformation::SetTrackParticleID (G4int trackParticleID)
Referenced by TG4TrackManager::SetTrackInformation().
void TG4TrackInformation::SetParentParticleID (G4int parentParticleID)
Referenced by TG4TrackManager::SetParentToTrackInformation().
void TG4TrackInformation::SetPDGLifetime (G4double pdgLifetime)
Referenced by TG4StepManager::ForceDecayTime().
void TG4TrackInformation::SetPDGEncoding (G4int pdgEncoding)
Referenced by TG4StackPopper::PostStepDoIt().
void TG4TrackInformation::SetIsUserTrack (G4bool isUserTrack)
Referenced by TG4StackPopper::PostStepDoIt().
void TG4TrackInformation::SetStop (G4bool stop)
Referenced by TG4SteppingAction::ProcessTrackIfBelowCut().
G4int TG4TrackInformation::GetTrackParticleID () const
Referenced by TG4TrackManager::SetParentToTrackInformation(), and TG4TrackManager::SetTrackInformation().
G4int TG4TrackInformation::GetParentParticleID () const
Referenced by TG4TrackManager::TrackToStack().
G4double TG4TrackInformation::GetPDGLifetime () const
Referenced by TG4TrackManager::SetBackPDGLifetime().
G4int TG4TrackInformation::GetPDGEncoding () const
Referenced by TG4StepManager::TrackPid().
G4bool TG4TrackInformation::IsUserTrack () const
Referenced by TG4TrackManager::IsUserTrack(), and TG4TrackManager::SaveSecondaries().
G4bool TG4TrackInformation::IsStop () const
Referenced by TG4VSpecialCuts::PostStepGetPhysicalInteractionLength().
Member Data Documentation
G4int TG4TrackInformation::fTrackParticleID private
the index of track particle in VMC stack
Definition at line 66 of file TG4TrackInformation.h.
Referenced by Print().
G4int TG4TrackInformation::fParentParticleID private
the index of parent track in VMC stack
Definition at line 67 of file TG4TrackInformation.h.
Referenced by Print().
G4double TG4TrackInformation::fPDGLifetime private
the original particle PDG lifetime
Definition at line 68 of file TG4TrackInformation.h.
G4double TG4TrackInformation::fPDGEncoding private
the particle PDG encoding
Definition at line 69 of file TG4TrackInformation.h.
G4bool TG4TrackInformation::fIsUserTrack private
true if defined by user and not primary track
Definition at line 70 of file TG4TrackInformation.h.
Referenced by Print().
G4bool TG4TrackInformation::fStop private
true if track should be stopped
Definition at line 71 of file TG4TrackInformation.h.
Referenced by Print().
The documentation for this class was generated from the following files:
source/physics/include/TG4TrackInformation.h
source/physics/src/TG4TrackInformation.cxx