Geant4 VMC: TG4RegionsManager Class Reference
TG4RegionsManager Class Reference
run
Manager class for converting VMC cuts in energy in G4 regions.
#include <TG4RegionsManager.h>
Public Member Functions
TG4RegionsManager ()
virtual ~TG4RegionsManager ()
void DefineRegions ()
void CheckRegions () const
void PrintRegions () const
void DumpRegion (const G4String &volName) const
void SetRangePrecision (G4int precision)
Set the precision for calculating ranges.
void SetApplyForGamma (G4bool applyForGamma)
Set the option to apply range cuts for gamma (default is true)
void SetApplyForElectron (G4bool applyForElectron)
Set the option to apply range cuts for e- (default is true)
void SetApplyForPositron (G4bool applyForPositron)
Set the option to apply range cuts for e+ (default is true)
void SetApplyForProton (G4bool applyForProton)
Set the option to apply range cuts for proton (default is true)
void SetCheck (G4bool isCheck)
Set the option to perform consistency check.
void SetPrint (G4bool isPrint)
Set the option to print all regions.
G4int GetRangePrecision () const
Return the precision for calculating ranges.
G4bool GetApplyForGamma () const
Return the option to apply range cuts for gamma.
G4bool GetApplyForElectron () const
Return the option to apply range cuts for e+.
G4bool GetApplyForPositron () const
Return the option to apply range cuts for positron.
G4bool GetApplyForProton () const
Return the option to apply range cuts for proton.
G4bool IsCheck () const
Return the option to perform consistency check.
G4bool IsPrint () const
Return the option to print all regions.
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Static Public Member Functions
static TG4RegionsManager * Instance ()
Return the singleton instance.
Private Member Functions
TG4RegionsManager (const TG4RegionsManager &right)
Not implemented.
TG4RegionsManager & operator= (const TG4RegionsManager &right)
Not implemented.
G4double GetGlobalEnergyCut (TG4G3Cut cutType) const
G4double GetEnergyCut (TG4Limits *limits, TG4G3Cut cutType, G4double globalCutValue) const
G4bool Iterate (G4double energyCut, G4double &lowerCut, G4double &higherCut, G4double defaultRangeCut, G4double lowEdgeEnergy, G4double highEdgeEnergy, G4int nbin, std::map< G4double, G4double > &map, std::map< G4double, G4double >::const_iterator &it, G4Material *material, G4VRangeToEnergyConverter &converter) const
G4double ConvertEnergyToRange (G4double energyCut, G4Material *material, G4VRangeToEnergyConverter &converter, G4double defaultRangeValue) const
G4double GetRangeCut (G4double energyCut, G4Material *material, G4VRangeToEnergyConverter &converter, G4double defaultRangeValue) const
G4bool IsCoupleUsedInTheRegion (const G4MaterialCutsCouple *couple, const G4Region *region) const
G4bool CheckCut (TG4Limits *limits, TG4G3Cut cut, const G4String &particleName, G4double energy, G4double range) const
void CheckRegionsRanges () const
void CheckRegionsInGeometry () const
Private Attributes
TG4RegionsMessenger fMessenger
messenger
G4int fRangePrecision
the precision for calculating ranges
G4bool fApplyForGamma
option to apply range cuts for gamma (default is true)
G4bool fApplyForElectron
option to apply range cuts for e- (default is true)
G4bool fApplyForPositron
option to apply range cuts for e+ (default is true)
G4bool fApplyForProton
option to apply range cuts for proton (default is true)
G4bool fIsCheck
option to perform consistency check (by default false)
G4bool fIsPrint
option to print all regions
Static Private Attributes
static TG4RegionsManager * fgInstance = 0
the singleton instance
static const G4int fgkDefaultRangePrecision = 2
the default precision for calculating ranges
static const G4double fgkRangeTolerance = 1e-3 * mm
the tolerance (absolute) for comparing range values
static const G4double fgkEnergyTolerance = 1e-06
the tolerance (relative) for comparing energy cut values
static const G4int fgkNofBins = 10
the number of bins for search range iteration
static const G4int fgkMinRangeOrder = -3
the minimum range order
static const G4int fgkMaxRangeOrder = 6
the maximum range order
static const G4String fgkDefaultRegionName
the name of the region with default cuts
Detailed Description
Manager class for converting VMC cuts in energy in G4 regions.
The VMC cuts in energy can be defined via the following TVirtulaMC functions:
TVirtualMC::SetCut(..)
TVirtualMC::Gstpar(..)
The TG4RegionsManager class defined regions with cuts in range corresponding to the VMC energy cuts set by user following these rules:
If the VMC energy cut defined by user results in a range cut smaller than the default range cut value defined in user physics list, the VMC cut is ignored and the default range cut is used
The range cut is first evaluated within the range 1e-03mm to 1m; when the range cut order is found, it is refined up to given precision (2 orders of magnitude by default) within 10 values of each order and the range value with the closest energy still smaller than VMC cut is chosen.
It may happen that value cannot be refined up to given precision, then the best found value is returned.
The regions are defined only in case when the VMC cuts result in range cuts different from the range cuts in default region; then the region includes all logical volumes with a given material
As the range cuts do not match precisely to user defined energy cuts, the specialCuts process applies the energy cuts as tracking cuts when a particle with energy cut below threshold is generated.
User can select several levels of verbosity; the following information is then printed:
0 no output
1 number of regions added via VMC
2 the list of all volumes, the cuts in energy and calculated cuts in range
3 all evaluated energy values
Author
I. Hrivnacova; IPN Orsay
Definition at line 74 of file TG4RegionsManager.h.
Constructor & Destructor Documentation
TG4RegionsManager::TG4RegionsManager ()
Default constructor
Definition at line 51 of file TG4RegionsManager.cxx.
TG4RegionsManager::~TG4RegionsManager () virtual
Destructor
Definition at line 68 of file TG4RegionsManager.cxx.
TG4RegionsManager::TG4RegionsManager (const TG4RegionsManager & right) private
Not implemented.
Member Function Documentation
TG4RegionsManager * TG4RegionsManager::Instance () inline static
Return the singleton instance.
Definition at line 181 of file TG4RegionsManager.h.
Referenced by TG4RunAction::BeginOfRunAction().
void TG4RegionsManager::DefineRegions ()
Apply cuts defined in tracking media
Definition at line 475 of file TG4RegionsManager.cxx.
Referenced by TG4RunManager::LateInitialize().
void TG4RegionsManager::CheckRegions () const
Perform two checks:
if region properties are consistent with energy cuts defined in limits
if the region to which the volume belongs correspond to its material
Definition at line 670 of file TG4RegionsManager.cxx.
Referenced by TG4RunAction::BeginOfRunAction().
void TG4RegionsManager::PrintRegions () const
Loop over production cuts table and print all regions ranges and energy cuts
Definition at line 683 of file TG4RegionsManager.cxx.
Referenced by TG4RunAction::BeginOfRunAction().
void TG4RegionsManager::DumpRegion (const G4String & volName) const
Dump region properties for volume with given name
Definition at line 756 of file TG4RegionsManager.cxx.
Referenced by TG4RegionsMessenger::SetNewValue().
void TG4RegionsManager::SetRangePrecision (G4int precision) inline
Set the precision for calculating ranges.
Definition at line 184 of file TG4RegionsManager.h.
Referenced by TG4RegionsMessenger::SetNewValue().
void TG4RegionsManager::SetApplyForGamma (G4bool applyForGamma) inline
Set the option to apply range cuts for gamma (default is true)
Definition at line 191 of file TG4RegionsManager.h.
Referenced by TG4RegionsMessenger::SetNewValue().
void TG4RegionsManager::SetApplyForElectron (G4bool applyForElectron) inline
Set the option to apply range cuts for e- (default is true)
Definition at line 197 of file TG4RegionsManager.h.
void TG4RegionsManager::SetApplyForPositron (G4bool applyForPositron) inline
Set the option to apply range cuts for e+ (default is true)
Definition at line 203 of file TG4RegionsManager.h.
Referenced by TG4RegionsMessenger::SetNewValue().
void TG4RegionsManager::SetApplyForProton (G4bool applyForProton) inline
Set the option to apply range cuts for proton (default is true)
Definition at line 209 of file TG4RegionsManager.h.
Referenced by TG4RegionsMessenger::SetNewValue().
void TG4RegionsManager::SetCheck (G4bool isCheck) inline
Set the option to perform consistency check.
Definition at line 215 of file TG4RegionsManager.h.
Referenced by TG4RegionsMessenger::SetNewValue().
void TG4RegionsManager::SetPrint (G4bool isPrint) inline
Set the option to print all regions.
Definition at line 218 of file TG4RegionsManager.h.
Referenced by TG4RegionsMessenger::SetNewValue().
G4int TG4RegionsManager::GetRangePrecision () const inline
Return the precision for calculating ranges.
Definition at line 221 of file TG4RegionsManager.h.
G4bool TG4RegionsManager::GetApplyForGamma () const inline
Return the option to apply range cuts for gamma.
Definition at line 227 of file TG4RegionsManager.h.
G4bool TG4RegionsManager::GetApplyForElectron () const inline
Return the option to apply range cuts for e+.
Definition at line 233 of file TG4RegionsManager.h.
G4bool TG4RegionsManager::GetApplyForPositron () const inline
Return the option to apply range cuts for positron.
Definition at line 239 of file TG4RegionsManager.h.
G4bool TG4RegionsManager::GetApplyForProton () const inline
Return the option to apply range cuts for proton.
Definition at line 245 of file TG4RegionsManager.h.
G4bool TG4RegionsManager::IsCheck () const inline
Return the option to perform consistency check.
Definition at line 251 of file TG4RegionsManager.h.
G4bool TG4RegionsManager::IsPrint () const inline
Return the option to print all regions.
Definition at line 254 of file TG4RegionsManager.h.
TG4RegionsManager& TG4RegionsManager::operator= (const TG4RegionsManager & right) private
Not implemented.
G4double TG4RegionsManager::GetGlobalEnergyCut (TG4G3Cut cutType) const private
Return global cut in energy of given cutType. Return DBL_MAX if cut value is not defined
Definition at line 80 of file TG4RegionsManager.cxx.
Referenced by DefineRegions().
G4double TG4RegionsManager::GetEnergyCut (TG4Limits * limits, TG4G3Cut cutType, G4double globalCutValue) const private
Return cut in energy defined in limits of given cutType. Return DBL_MAX if cut value is not defined.
Definition at line 98 of file TG4RegionsManager.cxx.
Referenced by CheckCut(), DefineRegions(), and PrintRegions().
G4bool TG4RegionsManager::Iterate (G4double energyCut, G4double & lowerCut, G4double & higherCut, G4double defaultRangeCut, G4double lowEdgeEnergy, G4double highEdgeEnergy, G4int nbin, std::map< G4double, G4double > & map, std::map< G4double, G4double >::const_iterator & it, G4Material * material, G4VRangeToEnergyConverter & converter) const private
Helper function called from ConvertEnergyToRange() in each iteration
Definition at line 116 of file TG4RegionsManager.cxx.
Referenced by ConvertEnergyToRange().
G4double TG4RegionsManager::ConvertEnergyToRange (G4double energyCut, G4Material * material, G4VRangeToEnergyConverter & converter, G4double defaultRangeValue) const private
Estimate cut in range for given cut in energy. Return negative value if range cut is not fount.
Definition at line 163 of file TG4RegionsManager.cxx.
Referenced by GetRangeCut().
G4double TG4RegionsManager::GetRangeCut (G4double energyCut, G4Material * material, G4VRangeToEnergyConverter & converter, G4double defaultRangeValue) const private
Convert energy cuts in range cuts; return defaultRangeCut, if found value is smaller than default
Definition at line 262 of file TG4RegionsManager.cxx.
Referenced by DefineRegions().
G4bool TG4RegionsManager::IsCoupleUsedInTheRegion (const G4MaterialCutsCouple * couple, const G4Region * region) const private
Reimplemented G4ProductionCutsTable::IsCoupleUsedInTheRegion which is declared private
Definition at line 306 of file TG4RegionsManager.cxx.
Referenced by DumpRegion().
G4bool TG4RegionsManager::CheckCut (TG4Limits * limits, TG4G3Cut cut, const G4String & particleName, G4double energy, G4double range) const private
Check if energy from region properties is consistent with energy cuts defined in limits.
Definition at line 326 of file TG4RegionsManager.cxx.
Referenced by CheckRegionsRanges().
void TG4RegionsManager::CheckRegionsRanges () const private
Loop over production cuts table and check if region properties are consistent with energy cuts defined in limits
Definition at line 366 of file TG4RegionsManager.cxx.
Referenced by CheckRegions().
void TG4RegionsManager::CheckRegionsInGeometry () const private
Loop over all logical volumes and check if the region to which the volume belongs correspond to its material
Definition at line 430 of file TG4RegionsManager.cxx.
Referenced by CheckRegions().
Member Data Documentation
TG4RegionsManager * TG4RegionsManager::fgInstance = 0 static private
the singleton instance
Definition at line 143 of file TG4RegionsManager.h.
Referenced by Instance(), TG4RegionsManager(), and ~TG4RegionsManager().
const G4int TG4RegionsManager::fgkDefaultRangePrecision = 2 static private
the default precision for calculating ranges
Definition at line 145 of file TG4RegionsManager.h.
const G4double TG4RegionsManager::fgkRangeTolerance = 1e-3 * mm static private
the tolerance (absolute) for comparing range values
Definition at line 147 of file TG4RegionsManager.h.
Referenced by CheckCut().
const G4double TG4RegionsManager::fgkEnergyTolerance = 1e-06 static private
the tolerance (relative) for comparing energy cut values
Definition at line 149 of file TG4RegionsManager.h.
Referenced by CheckCut().
const G4int TG4RegionsManager::fgkNofBins = 10 static private
the number of bins for search range iteration
Definition at line 151 of file TG4RegionsManager.h.
Referenced by ConvertEnergyToRange().
const G4int TG4RegionsManager::fgkMinRangeOrder = -3 static private
the minimum range order
Definition at line 153 of file TG4RegionsManager.h.
Referenced by ConvertEnergyToRange().
const G4int TG4RegionsManager::fgkMaxRangeOrder = 6 static private
the maximum range order
Definition at line 155 of file TG4RegionsManager.h.
Referenced by ConvertEnergyToRange().
const G4String TG4RegionsManager::fgkDefaultRegionName static private
Initial value:
=
  "RegionWithDefaultCuts"
the name of the region with default cuts
Definition at line 157 of file TG4RegionsManager.h.
Referenced by CheckRegionsInGeometry(), and DefineRegions().
TG4RegionsMessenger TG4RegionsManager::fMessenger private
messenger
Definition at line 163 of file TG4RegionsManager.h.
G4int TG4RegionsManager::fRangePrecision private
the precision for calculating ranges
Definition at line 165 of file TG4RegionsManager.h.
Referenced by ConvertEnergyToRange(), GetRangePrecision(), and SetRangePrecision().
G4bool TG4RegionsManager::fApplyForGamma private
option to apply range cuts for gamma (default is true)
Definition at line 167 of file TG4RegionsManager.h.
Referenced by DefineRegions(), GetApplyForGamma(), and SetApplyForGamma().
G4bool TG4RegionsManager::fApplyForElectron private
option to apply range cuts for e- (default is true)
Definition at line 169 of file TG4RegionsManager.h.
Referenced by DefineRegions(), GetApplyForElectron(), and SetApplyForElectron().
G4bool TG4RegionsManager::fApplyForPositron private
option to apply range cuts for e+ (default is true)
Definition at line 171 of file TG4RegionsManager.h.
Referenced by DefineRegions(), GetApplyForPositron(), and SetApplyForPositron().
G4bool TG4RegionsManager::fApplyForProton private
option to apply range cuts for proton (default is true)
Definition at line 173 of file TG4RegionsManager.h.
Referenced by DefineRegions(), GetApplyForProton(), and SetApplyForProton().
G4bool TG4RegionsManager::fIsCheck private
option to perform consistency check (by default false)
Definition at line 175 of file TG4RegionsManager.h.
Referenced by IsCheck(), and SetCheck().
G4bool TG4RegionsManager::fIsPrint private
option to print all regions
Definition at line 177 of file TG4RegionsManager.h.
Referenced by IsPrint(), and SetPrint().
The documentation for this class was generated from the following files:
source/run/include/TG4RegionsManager.h
source/run/src/TG4RegionsManager.cxx