Geant4 VMC: TG4EmModelPhysics Class Reference
TG4EmModelPhysics Class Reference
physics_list
Physics builder which activates a selected EM energy loss and/or fluctuations model.
#include <TG4EmModelPhysics.h>
Public Member Functions
TG4EmModelPhysics (const G4String &name="EmModel")
TG4EmModelPhysics (G4int theVerboseLevel, const G4String &name="EmModel")
virtual ~TG4EmModelPhysics ()
Public Member Functions inherited from TG4VPhysicsConstructor
TG4VPhysicsConstructor (const G4String &name)
TG4VPhysicsConstructor (const G4String &name, G4int theVerboseLevel)
virtual ~TG4VPhysicsConstructor ()
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
Static Public Member Functions
static TG4EmModel GetEmModel (const G4String &modelName)
static G4String GetEmModelName (G4int modelType)
Protected Member Functions
virtual void ConstructParticle ()
Construct particles.
virtual void ConstructProcess ()
Construct physics processes.
Protected Member Functions inherited from TG4VPhysicsConstructor
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Private Member Functions
TG4EmModelPhysics (const TG4EmModelPhysics &right)
Not implemented.
TG4EmModelPhysics & operator= (const TG4EmModelPhysics &right)
Not implemented.
void AddModel (TG4EmModel model, const G4ParticleDefinition *particle, const G4String &regionName)
void AddModels (const std::vector< TG4ModelConfiguration * > &models)
Detailed Description
Physics builder which activates a selected EM energy loss and/or fluctuations model.
In this implementation, G4PAIModel, G4PAIPhotModel and a special UrbanMsc model tuned for ALICE EMCAL are supported. Other models available in Geant4 can be added on user requests.
Author
I. Hrivnacova; IPN Orsay
Definition at line 53 of file TG4EmModelPhysics.h.
Constructor & Destructor Documentation
TG4EmModelPhysics::TG4EmModelPhysics (const G4String & name = "EmModel")
Standard constructor
Definition at line 91 of file TG4EmModelPhysics.cxx.
TG4EmModelPhysics::TG4EmModelPhysics (G4int theVerboseLevel, const G4String & name = "EmModel")
Standard constructor
Definition at line 102 of file TG4EmModelPhysics.cxx.
TG4EmModelPhysics::~TG4EmModelPhysics () virtual
Destructor
Definition at line 114 of file TG4EmModelPhysics.cxx.
TG4EmModelPhysics::TG4EmModelPhysics (const TG4EmModelPhysics & right) private
Not implemented.
Member Function Documentation
TG4EmModel TG4EmModelPhysics::GetEmModel (const G4String & modelName) static
Return the model tope for given model name
Definition at line 42 of file TG4EmModelPhysics.cxx.
Referenced by AddModels().
G4String TG4EmModelPhysics::GetEmModelName (G4int modelType) static
Return model name for given model type
Definition at line 66 of file TG4EmModelPhysics.cxx.
Referenced by AddModel(), and GetEmModel().
void TG4EmModelPhysics::ConstructParticle () protected virtual
Construct particles.
Instantiate particles - nothing to be done here
Implements TG4VPhysicsConstructor.
Definition at line 283 of file TG4EmModelPhysics.cxx.
void TG4EmModelPhysics::ConstructProcess () protected virtual
Construct physics processes.
Loop over all particles and their processes and check if the process is present in the map
Implements TG4VPhysicsConstructor.
Definition at line 289 of file TG4EmModelPhysics.cxx.
TG4EmModelPhysics& TG4EmModelPhysics::operator= (const TG4EmModelPhysics & right) private
Not implemented.
void TG4EmModelPhysics::AddModel (TG4EmModel model, const G4ParticleDefinition * particle, const G4String & regionName) private
Add selected EM model to given particle, process and region. If regionName is not set, the model is set to the world region.
Definition at line 124 of file TG4EmModelPhysics.cxx.
Referenced by AddModels().
void TG4EmModelPhysics::AddModels (const std::vector< TG4ModelConfiguration * > & models) private
Loop over all particles and their processes and check if the process is present in the map
Definition at line 223 of file TG4EmModelPhysics.cxx.
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
source/physics_list/include/TG4EmModelPhysics.h
source/physics_list/src/TG4EmModelPhysics.cxx