Geant4 VMC: TG4ModelConfigurationManager Class Reference
TG4ModelConfigurationManager Class Reference
physics_list
The model configuration vector with suitable setters and a messenger.
#include <TG4ModelConfigurationManager.h>
Public Types
typedef std::vector< TG4ModelConfiguration * > ModelConfigurationVector
Public Member Functions
TG4ModelConfigurationManager (const G4String &name, const G4String &availableModels="")
virtual ~TG4ModelConfigurationManager ()
void CreateRegions ()
void SetModel (const G4String &modelName)
void SetModelParticles (const G4String &modelName, const G4String &particles)
void SetModelRegions (const G4String &modelName, const G4String &regions)
G4String GetName () const
G4String GetAvailableModels () const
TG4ModelConfiguration * GetModelConfiguration (const G4String &modelName, G4bool warn=true) const
const ModelConfigurationVector & GetVector () const
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Private Member Functions
TG4ModelConfigurationManager (const TG4ModelConfigurationManager &right)
Not implemented.
TG4ModelConfigurationManager & operator= (const TG4ModelConfigurationManager &right)
Not implemented.
void SetRegionsNames ()
Private Attributes
TG4ModelConfigurationMessenger * fMessenger
Messenger.
G4String fName
The associated physics builder name.
G4String fAvailableModels
List of available models.
ModelConfigurationVector fVector
Vector of registered model configurations.
G4bool fCreateRegionsDone
Info whether regions were constructed.
Detailed Description
The model configuration vector with suitable setters and a messenger.
Author
I. Hrivnacova; IPN Orsay
Definition at line 32 of file TG4ModelConfigurationManager.h.
Member Typedef Documentation
typedef std::vector<TG4ModelConfiguration*> TG4ModelConfigurationManager::ModelConfigurationVector
Definition at line 35 of file TG4ModelConfigurationManager.h.
Constructor & Destructor Documentation
TG4ModelConfigurationManager::TG4ModelConfigurationManager (const G4String & name, const G4String & availableModels = "")
Standard constructor
Definition at line 35 of file TG4ModelConfigurationManager.cxx.
TG4ModelConfigurationManager::~TG4ModelConfigurationManager () virtual
Destructor
Definition at line 56 of file TG4ModelConfigurationManager.cxx.
TG4ModelConfigurationManager::TG4ModelConfigurationManager (const TG4ModelConfigurationManager & right) private
Not implemented.
Member Function Documentation
void TG4ModelConfigurationManager::CreateRegions ()
Create regions for all registered models
Definition at line 131 of file TG4ModelConfigurationManager.cxx.
Referenced by TG4GeometryManager::ConstructSDandField().
void TG4ModelConfigurationManager::SetModel (const G4String & modelName)
Set an extra EM model with the given name.
Definition at line 199 of file TG4ModelConfigurationManager.cxx.
Referenced by TG4VUserFastSimulation::SetModel(), and TG4ModelConfigurationMessenger::SetNewValue().
void TG4ModelConfigurationManager::SetModelParticles (const G4String & modelName, const G4String & particles)
Set particles for the physics model for given medium.
Definition at line 219 of file TG4ModelConfigurationManager.cxx.
Referenced by TG4VUserFastSimulation::SetModelParticles(), and TG4ModelConfigurationMessenger::SetNewValue().
void TG4ModelConfigurationManager::SetModelRegions (const G4String & modelName, const G4String & regions)
Set regions for the physics model for given medium.
Definition at line 240 of file TG4ModelConfigurationManager.cxx.
Referenced by TG4VUserFastSimulation::SetModelRegions(), and TG4ModelConfigurationMessenger::SetNewValue().
G4String TG4ModelConfigurationManager::GetName () const inline
Return the associated physics builder name
Definition at line 87 of file TG4ModelConfigurationManager.h.
Referenced by TG4ModelConfigurationMessenger::TG4ModelConfigurationMessenger().
G4String TG4ModelConfigurationManager::GetAvailableModels () const inline
Return the list of available models
Definition at line 93 of file TG4ModelConfigurationManager.h.
TG4ModelConfiguration * TG4ModelConfigurationManager::GetModelConfiguration (const G4String & modelName, G4bool warn = true) const
Return the model configuration via specified model name; print warning if a configuration is not found
Definition at line 261 of file TG4ModelConfigurationManager.cxx.
Referenced by TG4VUserFastSimulation::Register(), SetModel(), SetModelParticles(), and SetModelRegions().
const TG4ModelConfigurationManager::ModelConfigurationVector & TG4ModelConfigurationManager::GetVector () const inline
Return the vector of registered model configurations
Definition at line 100 of file TG4ModelConfigurationManager.h.
Referenced by TG4FastSimulationPhysics::ConstructProcess(), and TG4EmModelPhysics::ConstructProcess().
TG4ModelConfigurationManager& TG4ModelConfigurationManager::operator= (const TG4ModelConfigurationManager & right) private
Not implemented.
void TG4ModelConfigurationManager::SetRegionsNames () private
Set the regions names (corresponding to material names) to model configurations. This conversion is needed to be consistent with regions defined with special cuts, which are defined per materiials.
Definition at line 73 of file TG4ModelConfigurationManager.cxx.
Referenced by CreateRegions().
Member Data Documentation
TG4ModelConfigurationMessenger* TG4ModelConfigurationManager::fMessenger private
Messenger.
messenger
Definition at line 70 of file TG4ModelConfigurationManager.h.
Referenced by TG4ModelConfigurationManager(), and ~TG4ModelConfigurationManager().
G4String TG4ModelConfigurationManager::fName private
The associated physics builder name.
Definition at line 73 of file TG4ModelConfigurationManager.h.
Referenced by GetName().
G4String TG4ModelConfigurationManager::fAvailableModels private
List of available models.
Definition at line 76 of file TG4ModelConfigurationManager.h.
Referenced by GetAvailableModels().
ModelConfigurationVector TG4ModelConfigurationManager::fVector private
Vector of registered model configurations.
Definition at line 79 of file TG4ModelConfigurationManager.h.
Referenced by CreateRegions(), GetModelConfiguration(), GetVector(), SetModel(), SetRegionsNames(), and ~TG4ModelConfigurationManager().
G4bool TG4ModelConfigurationManager::fCreateRegionsDone private
Info whether regions were constructed.
Definition at line 82 of file TG4ModelConfigurationManager.h.
Referenced by CreateRegions().
The documentation for this class was generated from the following files:
source/global/include/TG4ModelConfigurationManager.h
source/global/src/TG4ModelConfigurationManager.cxx