Geant4 VMC: TG4VUserPostDetConstruction Class Reference
TG4VUserPostDetConstruction Class Reference abstract
geometry
The abstract base class for user defined class to customize geometry.
#include <TG4VUserPostDetConstruction.h>
Public Member Functions
TG4VUserPostDetConstruction ()
virtual ~TG4VUserPostDetConstruction ()
virtual void Construct ()=0
Method to be overriden by user.
Private Member Functions
TG4VUserPostDetConstruction (const TG4VUserPostDetConstruction &right)
Not implemented.
TG4VUserPostDetConstruction & operator= (const TG4VUserPostDetConstruction &right)
Not implemented.
Detailed Description
The abstract base class for user defined class to customize geometry.
An implemented use case is a user customization of magnetic field equation of motion and its stepper.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 29 of file TG4VUserPostDetConstruction.h.
Constructor & Destructor Documentation
TG4VUserPostDetConstruction::TG4VUserPostDetConstruction () inline
Definition at line 32 of file TG4VUserPostDetConstruction.h.
Referenced by ~TG4VUserPostDetConstruction().
virtual TG4VUserPostDetConstruction::~TG4VUserPostDetConstruction () inline virtual
Definition at line 33 of file TG4VUserPostDetConstruction.h.
TG4VUserPostDetConstruction::TG4VUserPostDetConstruction (const TG4VUserPostDetConstruction & right) private
Not implemented.
Member Function Documentation
virtual void TG4VUserPostDetConstruction::Construct () pure virtual
Method to be overriden by user.
Referenced by TG4GeometryManager::ConstructSDandField(), and ~TG4VUserPostDetConstruction().
TG4VUserPostDetConstruction& TG4VUserPostDetConstruction::operator= (const TG4VUserPostDetConstruction & right) private
Not implemented.
Referenced by ~TG4VUserPostDetConstruction().
The documentation for this class was generated from the following file:
source/geometry/include/TG4VUserPostDetConstruction.h