Geant4 VMC: TG4Limits Class Reference
TG4Limits Class Reference
global
Extended G4UserLimits class.
#include <TG4Limits.h>
Public Member Functions
TG4Limits (const TG4G3CutVector &cuts, const TG4G3ControlVector &controls)
TG4Limits (const G4String &name, const TG4G3CutVector &cuts, const TG4G3ControlVector &controls)
TG4Limits (const G4UserLimits &g4Limits, const TG4G3CutVector &cuts, const TG4G3ControlVector &controls)
TG4Limits (const TG4Limits &right)
virtual ~TG4Limits ()
TG4Limits & operator= (const TG4Limits &right)
void SetName (const G4String &name)
void SetG3Cut (TG4G3Cut cut, G4double cutValue)
void SetG3Control (TG4G3Control control, TG4G3ControlValue controlValue)
G4bool Update (const TG4G3ControlVector &controls)
void SetG3DefaultCuts ()
void SetG3DefaultControls ()
void SetCurrentMaxAllowedStep (G4double step)
void SetDefaultMaxAllowedStep ()
void SetMaxAllowedStepBack ()
void Print () const
G4String GetName () const
G4double GetMaxUserStep () const
const TG4G3CutVector * GetCutVector () const
const TG4G3ControlVector * GetControlVector () const
G4bool IsCut () const
G4bool IsControl () const
virtual G4double GetUserMinEkine (const G4Track &track)
G4double GetMinEkineForGamma (const G4Track &track) const
G4double GetMinEkineForElectron (const G4Track &track) const
G4double GetMinEkineForEplus (const G4Track &track) const
G4double GetMinEkineForChargedHadron (const G4Track &track) const
G4double GetMinEkineForNeutralHadron (const G4Track &track) const
G4double GetMinEkineForMuon (const G4Track &track) const
G4double GetMinEkineForOther (const G4Track &track) const
TG4G3ControlValue GetControl (G4VProcess *process) const
Static Public Member Functions
static G4int GetNofLimits ()
Private Member Functions
TG4Limits ()
Not implemented.
void Initialize (const TG4G3CutVector &cuts, const TG4G3ControlVector &controls)
Private Attributes
G4String fName
name
G4bool fIsCut
true if any cut value is set
G4bool fIsControl
true if any control value is set
TG4G3CutVector fCutVector
the vector of G3 cut values
TG4G3ControlVector fControlVector
the vector of G3 control values
G4double fDefaultMaxStep
the default max step value
Static Private Attributes
static G4int fgCounter = 0
counter
Detailed Description
Extended G4UserLimits class.
Class extends G4UserLimits base class with the vectors of kinetic energy cuts and control process flags data members.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 37 of file TG4Limits.h.
Constructor & Destructor Documentation
TG4Limits::TG4Limits (const TG4G3CutVector & cuts, const TG4G3ControlVector & controls)
Standard constructor
Definition at line 22 of file TG4Limits.cxx.
TG4Limits::TG4Limits (const G4String & name, const TG4G3CutVector & cuts, const TG4G3ControlVector & controls)
Standard constructor with specified name
Definition at line 41 of file TG4Limits.cxx.
TG4Limits::TG4Limits (const G4UserLimits & g4Limits, const TG4G3CutVector & cuts, const TG4G3ControlVector & controls)
Standard constructor with specified g4Limits
Definition at line 60 of file TG4Limits.cxx.
TG4Limits::TG4Limits (const TG4Limits & right)
Copy constructor
Definition at line 94 of file TG4Limits.cxx.
TG4Limits::~TG4Limits () virtual
Destructor
Definition at line 109 of file TG4Limits.cxx.
TG4Limits::TG4Limits () private
Not implemented.
Default constructor
Definition at line 76 of file TG4Limits.cxx.
Member Function Documentation
TG4Limits & TG4Limits::operator= (const TG4Limits & right)
Assignment operator
Definition at line 119 of file TG4Limits.cxx.
G4int TG4Limits::GetNofLimits () inline static
Return the total number of all TG4Limits objects
Definition at line 107 of file TG4Limits.h.
Referenced by TG4GeometryServices::PrintStatistics().
void TG4Limits::SetName (const G4String & name) inline
Set name
Definition at line 125 of file TG4Limits.h.
Referenced by TG4GeometryManager::SetUserLimits().
void TG4Limits::SetG3Cut (TG4G3Cut cut, G4double cutValue)
Set the cut value for the specified cut.
Definition at line 174 of file TG4Limits.cxx.
Referenced by TG4PhysicsManager::GstparCut().
void TG4Limits::SetG3Control (TG4G3Control control, TG4G3ControlValue controlValue)
Set the process control value for the specified control.
Definition at line 185 of file TG4Limits.cxx.
Referenced by TG4PhysicsManager::GstparControl().
G4bool TG4Limits::Update (const TG4G3ControlVector & controls)
Update controls in a special way. Return true if some control in fControlVector is after update still set.
Definition at line 205 of file TG4Limits.cxx.
Referenced by TG4GeometryManager::SetUserLimits().
void TG4Limits::SetG3DefaultCuts ()
Set the G3 default cut values for all cuts.
Definition at line 196 of file TG4Limits.cxx.
void TG4Limits::SetG3DefaultControls ()
Set the G3 default process control values for all flags.
Definition at line 221 of file TG4Limits.cxx.
void TG4Limits::SetCurrentMaxAllowedStep (G4double step)
Set the new value of max step in the base class
Definition at line 230 of file TG4Limits.cxx.
Referenced by TG4StepManager::SetMaxStep().
void TG4Limits::SetDefaultMaxAllowedStep ()
Set the max stap value in base class as the default value (in fDefaultMaxStep)
Definition at line 241 of file TG4Limits.cxx.
Referenced by TG4GeometryManager::SetUserLimits().
void TG4Limits::SetMaxAllowedStepBack ()
Set the default max stap value (stored in fDefaultMaxStep) back as the max step value in the base class
Definition at line 253 of file TG4Limits.cxx.
Referenced by TG4StepManager::SetMaxStepBack().
void TG4Limits::Print () const
Print limits.
Definition at line 265 of file TG4Limits.cxx.
Referenced by TG4Medium::Print(), TG4GeometryServices::PrintLimits(), and TG4GeometryServices::PrintVolumeLimits().
G4String TG4Limits::GetName () const inline
Return name
Definition at line 131 of file TG4Limits.h.
Referenced by TG4GeometryServices::FindLimits(), TG4GeometryServices::FindLimits2(), and TG4MCGeometry::GetMedium().
G4double TG4Limits::GetMaxUserStep () const inline
Return max step
Definition at line 137 of file TG4Limits.h.
Referenced by TG4MCGeometry::GetMedium().
const TG4G3CutVector * TG4Limits::GetCutVector () const inline
Return the vector of G3 cut values
Definition at line 143 of file TG4Limits.h.
Referenced by TG4RegionsManager::GetEnergyCut(), and TG4SteppingAction::ProcessTrackIfBelowCut().
const TG4G3ControlVector * TG4Limits::GetControlVector () const inline
Return the vector of G3 control values
Definition at line 149 of file TG4Limits.h.
G4bool TG4Limits::IsCut () const inline
Return true if any cut value is set
Definition at line 113 of file TG4Limits.h.
G4bool TG4Limits::IsControl () const inline
Return true if any control value is set
Definition at line 119 of file TG4Limits.h.
Referenced by TG4SpecialControlsV2::SetSwitch().
G4double TG4Limits::GetUserMinEkine (const G4Track & track) virtual
Return the kinetic energy cut parameter. !! The cuts values defined if fCutVector are applied only via TG4SpecialCuts process.
Definition at line 164 of file TG4Limits.cxx.
G4double TG4Limits::GetMinEkineForGamma (const G4Track & track) const
Return the cut value for gamma.
Definition at line 284 of file TG4Limits.cxx.
Referenced by TG4SpecialCutsForGamma::GetMinEkine().
G4double TG4Limits::GetMinEkineForElectron (const G4Track & track) const
Return the cut value for e-.
Definition at line 295 of file TG4Limits.cxx.
Referenced by TG4SpecialCutsForElectron::GetMinEkine().
G4double TG4Limits::GetMinEkineForEplus (const G4Track & track) const
Return the cut value for e-.
Definition at line 306 of file TG4Limits.cxx.
Referenced by TG4SpecialCutsForEplus::GetMinEkine().
G4double TG4Limits::GetMinEkineForChargedHadron (const G4Track & track) const
Return the cut value for charged hadron.
Definition at line 317 of file TG4Limits.cxx.
Referenced by TG4SpecialCutsForChargedHadron::GetMinEkine().
G4double TG4Limits::GetMinEkineForNeutralHadron (const G4Track & track) const
Return the cut value for neutral hadron.
Definition at line 328 of file TG4Limits.cxx.
Referenced by TG4SpecialCutsForNeutralHadron::GetMinEkine().
G4double TG4Limits::GetMinEkineForMuon (const G4Track & track) const
Return the cut value for neutral muon.
Definition at line 339 of file TG4Limits.cxx.
Referenced by TG4SpecialCutsForMuon::GetMinEkine().
G4double TG4Limits::GetMinEkineForOther (const G4Track & track) const
Return the cut value for other particle.
Definition at line 350 of file TG4Limits.cxx.
Referenced by TG4SpecialCutsForOther::GetMinEkine().
TG4G3ControlValue TG4Limits::GetControl (G4VProcess * process) const
Return the flag value for the particle associated with the specified process.
Definition at line 361 of file TG4Limits.cxx.
Referenced by TG4SpecialControlsV2::ApplyControls().
void TG4Limits::Initialize (const TG4G3CutVector & cuts, const TG4G3ControlVector & controls) private
Initialization.
Definition at line 143 of file TG4Limits.cxx.
Referenced by TG4Limits().
Member Data Documentation
G4int TG4Limits::fgCounter = 0 static private
counter
Definition at line 94 of file TG4Limits.h.
Referenced by GetNofLimits(), Initialize(), and TG4Limits().
G4String TG4Limits::fName private
name
Definition at line 97 of file TG4Limits.h.
Referenced by GetName(), operator=(), Print(), and SetName().
G4bool TG4Limits::fIsCut private
true if any cut value is set
Definition at line 98 of file TG4Limits.h.
Referenced by GetMinEkineForChargedHadron(), GetMinEkineForElectron(), GetMinEkineForEplus(), GetMinEkineForGamma(), GetMinEkineForMuon(), GetMinEkineForNeutralHadron(), GetMinEkineForOther(), Initialize(), IsCut(), operator=(), Print(), SetG3Cut(), and SetG3DefaultCuts().
G4bool TG4Limits::fIsControl private
true if any control value is set
Definition at line 99 of file TG4Limits.h.
Referenced by GetControl(), Initialize(), IsControl(), operator=(), Print(), SetG3Control(), SetG3DefaultControls(), and Update().
TG4G3CutVector TG4Limits::fCutVector private
the vector of G3 cut values
Definition at line 100 of file TG4Limits.h.
Referenced by GetCutVector(), GetMinEkineForChargedHadron(), GetMinEkineForElectron(), GetMinEkineForEplus(), GetMinEkineForGamma(), GetMinEkineForMuon(), GetMinEkineForNeutralHadron(), GetMinEkineForOther(), Initialize(), operator=(), Print(), SetG3Control(), SetG3Cut(), and SetG3DefaultCuts().
TG4G3ControlVector TG4Limits::fControlVector private
the vector of G3 control values
Definition at line 101 of file TG4Limits.h.
Referenced by GetControl(), GetControlVector(), Initialize(), operator=(), Print(), SetG3Control(), SetG3DefaultControls(), and Update().
G4double TG4Limits::fDefaultMaxStep private
the default max step value
Definition at line 102 of file TG4Limits.h.
Referenced by SetDefaultMaxAllowedStep(), and SetMaxAllowedStepBack().
The documentation for this class was generated from the following files:
source/global/include/TG4Limits.h
source/global/src/TG4Limits.cxx