Geant4 VMC: TG4RunManager Class Reference
TG4RunManager Class Reference
run
Geant4 implementation of the TVirtualMC interface methods for access to Geant4 at run level.
#include <TG4RunManager.h>
Public Member Functions
TG4RunManager (TG4RunConfiguration *configuration, int argc=0, char **argv=0)
virtual ~TG4RunManager ()
void Initialize ()
void LateInitialize ()
void CacheMCStack ()
void ProcessEvent ()
Bool_t ProcessRun (G4int nofEvents)
Bool_t FinishRun ()
Int_t CurrentEvent () const
Bool_t SecondariesAreOrdered () const
void CreateGeantUI ()
void StartGeantUI ()
void StartRootUI ()
void ProcessGeantMacro (G4String macroName)
void ProcessRootMacro (G4String macroName)
void ProcessGeantCommand (G4String command)
void ProcessRootCommand (G4String command)
void UseG3Defaults ()
void UseRootRandom (G4bool useRootRandom)
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Static Public Member Functions
static TG4RunManager * Instance ()
Private Member Functions
TG4RunManager ()
Not implemented.
TG4RunManager (const TG4RunManager &right)
Not implemented.
TG4RunManager & operator= (const TG4RunManager &right)
Not implemented.
void ConfigureRunManager ()
void CloneRootNavigatorForWorker ()
void FilterARGV (const G4String &option)
void CreateRootUI ()
void SetRandomSeed ()
Private Attributes
G4RunManager * fRunManager
G4RunManager.
TG4RunMessenger fMessenger
messenger
TG4RunConfiguration * fRunConfiguration
TG4RunConfiguration.
TG4RegionsManager * fRegionsManager
regions manager
G4UIExecutive * fGeantUISession
G4 UI.
TApplication * fRootUISession
Root UI.
G4bool fRootUIOwner
ownership of Root UI
G4int fARGC
argc
char ** fARGV
argv
G4bool fUseRootRandom
the option to use Root random number seed
G4bool fIsMCStackCached
the flag to cache MC stack only once
G4bool fHasEventByEventInitialization
Flag event-by-event processing.
G4int fNEventsProcessed
Number of events processed in event-by-event mode.
G4bool fInProcessRun
flag while being in BeamOn
Static Private Attributes
static TG4RunManager * fgMasterInstance = 0
master instance
static G4ThreadLocal TG4RunManager * fgInstance = 0
thread local instance
Detailed Description
Geant4 implementation of the TVirtualMC interface methods for access to Geant4 at run level.
It provides also methods for switching between Geant4 and Root UIs.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 43 of file TG4RunManager.h.
Constructor & Destructor Documentation
TG4RunManager::TG4RunManager (TG4RunConfiguration * configuration, int argc = 0, char ** argv = 0)
Standard constructor
Definition at line 80 of file TG4RunManager.cxx.
TG4RunManager::~TG4RunManager () virtual
Destructor
Definition at line 149 of file TG4RunManager.cxx.
TG4RunManager::TG4RunManager () private
Not implemented.
TG4RunManager::TG4RunManager (const TG4RunManager & right) private
Not implemented.
Member Function Documentation
TG4RunManager * TG4RunManager::Instance () inline static
Return this instance
Definition at line 121 of file TG4RunManager.h.
Referenced by TG4PrimaryGeneratorAction::GeneratePrimaries(), and TG4WorkerInitialization::WorkerRunStart().
void TG4RunManager::Initialize ()
Initialize G4.
Definition at line 389 of file TG4RunManager.cxx.
Referenced by TGeant4::Init().
void TG4RunManager::LateInitialize ()
Finish initialization of G4 after the G4Run initialization is finished.
Definition at line 413 of file TG4RunManager.cxx.
Referenced by TGeant4::BuildPhysics(), and TG4WorkerInitialization::WorkerRunStart().
void TG4RunManager::CacheMCStack ()
Cache the pointer to thread-local VMC stack
Definition at line 471 of file TG4RunManager.cxx.
Referenced by TG4PrimaryGeneratorAction::GeneratePrimaries().
void TG4RunManager::ProcessEvent ()
Replaying what is done in G4RunManager::BeamOn in order to initialize a run only once and process single events on user request
Definition at line 502 of file TG4RunManager.cxx.
Referenced by TGeant4::ProcessEvent().
Bool_t TG4RunManager::ProcessRun (G4int nofEvents)
Process Geant4 run.
Definition at line 522 of file TG4RunManager.cxx.
Referenced by TGeant4::ProcessRun().
Bool_t TG4RunManager::FinishRun ()
Definition at line 540 of file TG4RunManager.cxx.
Referenced by TGeant4::FinishRun(), and ProcessRun().
Int_t TG4RunManager::CurrentEvent () const
Return the number of the current event.
Definition at line 681 of file TG4RunManager.cxx.
Referenced by TGeant4::CurrentEvent().
Bool_t TG4RunManager::SecondariesAreOrdered () const
Since transition to G4SmartTrackStack in Geant4 9.6.x secondaries are not ordered even when the special stacking is activated.
Definition at line 690 of file TG4RunManager.cxx.
Referenced by TGeant4::SecondariesAreOrdered().
void TG4RunManager::CreateGeantUI ()
Create interactive Geant4.
Definition at line 567 of file TG4RunManager.cxx.
Referenced by TGeant4::Init(), and StartGeantUI().
void TG4RunManager::StartGeantUI ()
Start interactive/batch Geant4.
Definition at line 580 of file TG4RunManager.cxx.
Referenced by TGeant4::StartGeantUI().
void TG4RunManager::StartRootUI ()
Start interactive Root.
Definition at line 600 of file TG4RunManager.cxx.
Referenced by TG4RunMessenger::SetNewValue(), and TGeant4::StartRootUI().
void TG4RunManager::ProcessGeantMacro (G4String macroName)
Process Geant4 macro.
Definition at line 613 of file TG4RunManager.cxx.
Referenced by TGeant4::ProcessGeantMacro().
void TG4RunManager::ProcessRootMacro (G4String macroName)
Process Root macro.
Definition at line 622 of file TG4RunManager.cxx.
Referenced by TG4RunMessenger::SetNewValue().
void TG4RunManager::ProcessGeantCommand (G4String command)
Process Geant4 command.
Definition at line 638 of file TG4RunManager.cxx.
Referenced by TGeant4::ProcessGeantCommand(), and ProcessGeantMacro().
void TG4RunManager::ProcessRootCommand (G4String command)
Process Root command.
Definition at line 664 of file TG4RunManager.cxx.
Referenced by TG4RunMessenger::SetNewValue().
void TG4RunManager::UseG3Defaults ()
Control G3 defaults usage.
Definition at line 672 of file TG4RunManager.cxx.
Referenced by TG4RunMessenger::SetNewValue().
void TG4RunManager::UseRootRandom (G4bool useRootRandom) inline
Set the option whether to use Root random number seed
Definition at line 127 of file TG4RunManager.h.
Referenced by TG4RunMessenger::SetNewValue().
TG4RunManager& TG4RunManager::operator= (const TG4RunManager & right) private
Not implemented.
void TG4RunManager::ConfigureRunManager () private
Set the user action classes defined by TG4RunConfiguration to G4RunManager.
Definition at line 173 of file TG4RunManager.cxx.
Referenced by TG4RunManager().
void TG4RunManager::CloneRootNavigatorForWorker () private
Definition at line 293 of file TG4RunManager.cxx.
Referenced by TG4RunManager().
void TG4RunManager::FilterARGV (const G4String & option) private
Filter out the option argument from the arguments list fARGV, if present.
Definition at line 357 of file TG4RunManager.cxx.
Referenced by CreateRootUI().
void TG4RunManager::CreateRootUI () private
Get/Create Root interactive session
Definition at line 322 of file TG4RunManager.cxx.
Referenced by StartRootUI().
void TG4RunManager::SetRandomSeed () private
Pass the random number seed from fRandom to Geant4 random number generator
Definition at line 374 of file TG4RunManager.cxx.
Referenced by LateInitialize().
Member Data Documentation
TG4RunManager * TG4RunManager::fgMasterInstance = 0 static private
master instance
Definition at line 96 of file TG4RunManager.h.
Referenced by TG4RunManager(), and ~TG4RunManager().
G4ThreadLocal TG4RunManager * TG4RunManager::fgInstance = 0 static private
thread local instance
this instance
Definition at line 99 of file TG4RunManager.h.
Referenced by Instance(), TG4RunManager(), and ~TG4RunManager().
G4RunManager* TG4RunManager::fRunManager private
G4RunManager.
Definition at line 102 of file TG4RunManager.h.
Referenced by ConfigureRunManager(), CurrentEvent(), FinishRun(), Initialize(), ProcessEvent(), ProcessRun(), TG4RunManager(), and ~TG4RunManager().
TG4RunMessenger TG4RunManager::fMessenger private
messenger
Definition at line 103 of file TG4RunManager.h.
TG4RunConfiguration* TG4RunManager::fRunConfiguration private
TG4RunConfiguration.
Definition at line 104 of file TG4RunManager.h.
Referenced by CloneRootNavigatorForWorker(), ConfigureRunManager(), LateInitialize(), TG4RunManager(), and ~TG4RunManager().
TG4RegionsManager* TG4RunManager::fRegionsManager private
regions manager
Definition at line 105 of file TG4RunManager.h.
Referenced by ConfigureRunManager(), LateInitialize(), TG4RunManager(), and ~TG4RunManager().
G4UIExecutive* TG4RunManager::fGeantUISession private
G4 UI.
Definition at line 106 of file TG4RunManager.h.
Referenced by CreateGeantUI(), StartGeantUI(), TG4RunManager(), and ~TG4RunManager().
TApplication* TG4RunManager::fRootUISession private
Root UI.
Definition at line 107 of file TG4RunManager.h.
Referenced by CreateRootUI(), StartRootUI(), TG4RunManager(), and ~TG4RunManager().
G4bool TG4RunManager::fRootUIOwner private
ownership of Root UI
Definition at line 108 of file TG4RunManager.h.
Referenced by CreateRootUI(), and ~TG4RunManager().
G4int TG4RunManager::fARGC private
argc
Definition at line 109 of file TG4RunManager.h.
Referenced by CreateGeantUI(), CreateRootUI(), FilterARGV(), and TG4RunManager().
char** TG4RunManager::fARGV private
argv
Definition at line 110 of file TG4RunManager.h.
Referenced by CreateGeantUI(), CreateRootUI(), FilterARGV(), and TG4RunManager().
G4bool TG4RunManager::fUseRootRandom private
the option to use Root random number seed
Definition at line 111 of file TG4RunManager.h.
Referenced by LateInitialize(), and UseRootRandom().
G4bool TG4RunManager::fIsMCStackCached private
the flag to cache MC stack only once
Definition at line 112 of file TG4RunManager.h.
Referenced by CacheMCStack().
G4bool TG4RunManager::fHasEventByEventInitialization private
Flag event-by-event processing.
Definition at line 113 of file TG4RunManager.h.
Referenced by FinishRun(), ProcessEvent(), and ProcessRun().
G4int TG4RunManager::fNEventsProcessed private
Number of events processed in event-by-event mode.
Definition at line 115 of file TG4RunManager.h.
Referenced by FinishRun(), ProcessEvent(), and ProcessRun().
G4bool TG4RunManager::fInProcessRun private
flag while being in BeamOn
Definition at line 116 of file TG4RunManager.h.
Referenced by FinishRun(), and ProcessRun().
The documentation for this class was generated from the following files:
source/run/include/TG4RunManager.h
source/run/src/TG4RunManager.cxx