Geant4 VMC: TG4ProcessMCMap Class Reference
TG4ProcessMCMap Class Reference
physics
Maps G4 process names to TMCProcess code.
#include <TG4ProcessMCMap.h>
Public Types
typedef std::map< G4String, TMCProcess, std::less< G4String > > Map
The map of TMCProcess to strings.
typedef Map::iterator MapIterator
The iterator for the map of TMCProcess to strings.
typedef Map::const_iterator MapConstIterator
The constant iterator for the map of TMCProcess to strings.
Public Member Functions
TG4ProcessMCMap ()
virtual ~TG4ProcessMCMap ()
G4bool Add (G4VProcess *process, TMCProcess second)
G4bool Add (G4String processName, TMCProcess second)
void PrintAll () const
void Clear ()
TMCProcess GetMCProcess (const G4VProcess *process) const
TMCProcess GetMCProcess (const G4String &processName) const
G4String GetMCProcessName (const G4VProcess *process) const
G4String GetMCProcessName (const G4String &processName) const
Static Public Member Functions
static TG4ProcessMCMap * Instance ()
Private Member Functions
TG4ProcessMCMap (const TG4ProcessMCMap &right)
Not implemented.
TG4ProcessMCMap & operator= (const TG4ProcessMCMap &right)
Not implemented.
G4bool IsDefined (const G4String &processName)
Private Attributes
Map fMap
map container
Static Private Attributes
static TG4ProcessMCMap * fgInstance = 0
this instance
Detailed Description
Maps G4 process names to TMCProcess code.
Singleton map container for associated pairs of G4 process name and TMCProcess code.
Author
I. Hrivnacova; IPN Orsay
Definition at line 34 of file TG4ProcessMCMap.h.
Member Typedef Documentation
typedef std::map<G4String, TMCProcess, std::less<G4String> > TG4ProcessMCMap::Map
The map of TMCProcess to strings.
Definition at line 38 of file TG4ProcessMCMap.h.
typedef Map::iterator TG4ProcessMCMap::MapIterator
The iterator for the map of TMCProcess to strings.
Definition at line 41 of file TG4ProcessMCMap.h.
typedef Map::const_iterator TG4ProcessMCMap::MapConstIterator
The constant iterator for the map of TMCProcess to strings.
Definition at line 44 of file TG4ProcessMCMap.h.
Constructor & Destructor Documentation
TG4ProcessMCMap::TG4ProcessMCMap ()
Default constructor
Definition at line 26 of file TG4ProcessMCMap.cxx.
TG4ProcessMCMap::~TG4ProcessMCMap () virtual
Destructor
Definition at line 39 of file TG4ProcessMCMap.cxx.
TG4ProcessMCMap::TG4ProcessMCMap (const TG4ProcessMCMap & right) private
Not implemented.
Member Function Documentation
TG4ProcessMCMap * TG4ProcessMCMap::Instance () inline static
Return this instance
Definition at line 84 of file TG4ProcessMCMap.h.
Referenced by TG4ProcessMCMapPhysics::ConstructProcess(), TG4ProcessMCMapPhysics::FillMap(), and TG4ComposedPhysicsMessenger::SetNewValue().
G4bool TG4ProcessMCMap::Add (G4VProcess * process, TMCProcess second)
Add the pair to the map.
Definition at line 66 of file TG4ProcessMCMap.cxx.
Referenced by TG4ProcessMCMapPhysics::FillMap().
G4bool TG4ProcessMCMap::Add (G4String processName, TMCProcess second)
Add the pair to the map.
Definition at line 76 of file TG4ProcessMCMap.cxx.
void TG4ProcessMCMap::PrintAll () const
Dump the whole map.
Definition at line 90 of file TG4ProcessMCMap.cxx.
Referenced by TG4ComposedPhysicsMessenger::SetNewValue().
void TG4ProcessMCMap::Clear ()
Clear the map.
Definition at line 108 of file TG4ProcessMCMap.cxx.
TMCProcess TG4ProcessMCMap::GetMCProcess (const G4VProcess * process) const
Return TMCProcess code for the process with a given name.
Definition at line 116 of file TG4ProcessMCMap.cxx.
Referenced by TG4ProcessMCMapPhysics::ConstructProcess(), TG4PhysicsManager::GetMCProcess(), and GetMCProcessName().
TMCProcess TG4ProcessMCMap::GetMCProcess (const G4String & processName) const
Return TMCProcess code for the process with a given name.
Definition at line 126 of file TG4ProcessMCMap.cxx.
G4String TG4ProcessMCMap::GetMCProcessName (const G4VProcess * process) const
Return TMCProcess code for the process with a given name.
Definition at line 138 of file TG4ProcessMCMap.cxx.
G4String TG4ProcessMCMap::GetMCProcessName (const G4String & processName) const
Return TMCProcess code for the process with a given name.
Definition at line 148 of file TG4ProcessMCMap.cxx.
TG4ProcessMCMap& TG4ProcessMCMap::operator= (const TG4ProcessMCMap & right) private
Not implemented.
G4bool TG4ProcessMCMap::IsDefined (const G4String & processName) private
Return true if the first is already in the map.
Definition at line 51 of file TG4ProcessMCMap.cxx.
Referenced by Add().
Member Data Documentation
TG4ProcessMCMap * TG4ProcessMCMap::fgInstance = 0 static private
this instance
Definition at line 76 of file TG4ProcessMCMap.h.
Referenced by Instance(), TG4ProcessMCMap(), and ~TG4ProcessMCMap().
Map TG4ProcessMCMap::fMap private
map container
Definition at line 79 of file TG4ProcessMCMap.h.
Referenced by Add(), Clear(), GetMCProcess(), IsDefined(), and PrintAll().
The documentation for this class was generated from the following files:
source/physics/include/TG4ProcessMCMap.h
source/physics/src/TG4ProcessMCMap.cxx