Geant4 VMC: TG4G3Units Class Reference
TG4G3Units Class Reference
global
G3 default units of physical quantities;.
#include <TG4G3Units.h>
Public Member Functions
virtual ~TG4G3Units ()
Static Public Member Functions
static G4double Length ()
static G4double Angle ()
static G4double Time ()
static G4double Charge ()
static G4double Energy ()
static G4double Mass ()
static G4double MassDensity ()
static G4double AtomicWeight ()
static G4double Field ()
Private Member Functions
TG4G3Units ()
Static Private Attributes
static const G4double fgkLength = cm
G3 length unit.
static const G4double fgkAngle = deg
G3 angle unit.
static const G4double fgkTime = s
G3 time unit.
static const G4double fgkCharge = eplus
G3 charge unit.
static const G4double fgkEnergy = GeV
G3 energy unit.
static const G4double fgkMass = GeV
G3 mass unit.
static const G4double fgkMassDensity = g / cm3
G3 mass density unit.
static const G4double fgkAtomicWeight = g / mole
G3 atomic weight unit.
static const G4double fgkField = kilogauss
G3 magnetic field unit.
Detailed Description
G3 default units of physical quantities;.
All physical quantities returned by VMC are expressed in these units.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 27 of file TG4G3Units.h.
Constructor & Destructor Documentation
TG4G3Units::~TG4G3Units () virtual
Destructor
Definition at line 32 of file TG4G3Units.cxx.
TG4G3Units::TG4G3Units () private
Member Function Documentation
G4double TG4G3Units::Length () inline static
Return G3 length unit
Definition at line 60 of file TG4G3Units.h.
Referenced by TG4OpGeometryManager::AddUnit(), TG4StepManager::CurrentMaterial(), TG4StepManager::Gdtom(), TG4MagneticField::GetFieldValue(), TG4CachedMagneticField::GetFieldValue(), TG4OpGeometryManager::GetMaterial(), TG4MCGeometry::GetMaterial(), TG4ParticlesManager::GetParticlePosition(), TG4StepManager::GetSecondary(), TG4OpGeometryManager::Gfmate(), TG4StepManager::Gmtod(), TG4StepManager::MaxStep(), TG4TrackManager::PrimaryToStack(), TG4SteppingAction::ProcessTrackIfOutOfRegion(), TG4OpGeometryManager::SetCerenkov(), TG4StepManager::SetMaxStep(), TG4DetConstructionMessenger::SetNewValue(), TG4StepManager::TrackLength(), TG4StepManager::TrackPosition(), TG4StepManager::TrackStep(), and TG4TrackManager::TrackToStack().
G4double TG4G3Units::Angle () inline static
Return G3 angle unit
Definition at line 66 of file TG4G3Units.h.
G4double TG4G3Units::Time () inline static
Return G3 time unit
Definition at line 72 of file TG4G3Units.h.
Referenced by TG4ParticlesManager::AddParticle(), TG4OpGeometryManager::AddUnit(), TG4G3PhysicsManager::CheckCutWithTheVector(), TG4StepManager::ForceDecayTime(), TG4StepManager::GetSecondary(), TG4PhysicsManager::GstparCut(), TG4StackPopper::PostStepDoIt(), TG4TrackManager::PrimaryToStack(), TG4PhysicsManager::SetCut(), TG4StepManager::TrackPosition(), TG4StepManager::TrackTime(), TG4TrackManager::TrackToStack(), and TG4PrimaryGeneratorAction::TransformPrimaries().
G4double TG4G3Units::Charge () inline static
Return G3 chanrge unit
Definition at line 78 of file TG4G3Units.h.
Referenced by TG4ParticlesManager::AddParticle(), TG4PhysicsManager::ParticleCharge(), and TG4StepManager::TrackCharge().
G4double TG4G3Units::Energy () inline static
Return G3 energy unit
Definition at line 84 of file TG4G3Units.h.
Referenced by TG4ParticlesManager::AddParticle(), TG4ParticlesManager::AddParticleToPdgDatabase(), TG4OpGeometryManager::AddUnit(), TG4G3PhysicsManager::CheckCutWithTheVector(), TG4PhysicsManager::DefineIon(), TG4StepManager::Edep(), TG4StepManager::Etot(), TG4ParticlesManager::GetParticleMomentum(), TG4StepManager::GetSecondary(), TG4PhysicsManager::GstparCut(), TG4ExtDecayer::ImportDecayProducts(), TG4StepManager::NIELEdep(), TG4PhysicsManager::ParticleMass(), TG4TrackManager::PrimaryToStack(), TG4RegionsManager::PrintRegions(), TG4OpGeometryManager::SetCerenkov(), TG4PhysicsManager::SetCut(), TG4OpGeometryManager::SetMaterialProperty(), TG4StepManager::TrackMomentum(), TG4TrackManager::TrackToStack(), and TG4PrimaryGeneratorAction::TransformPrimaries().
G4double TG4G3Units::Mass () inline static
Return G3 mass unit
Definition at line 90 of file TG4G3Units.h.
Referenced by TG4StepManager::TrackMass().
G4double TG4G3Units::MassDensity () inline static
Return G3 mass density unit
Definition at line 96 of file TG4G3Units.h.
Referenced by TG4GeometryServices::CompareMaterial(), TG4StepManager::CurrentMaterial(), TG4OpGeometryManager::GetMaterial(), TG4MCGeometry::GetMaterial(), and TG4OpGeometryManager::Gfmate().
G4double TG4G3Units::AtomicWeight () inline static
Return G3 atomic weight unit
Definition at line 102 of file TG4G3Units.h.
Referenced by TG4GeometryServices::GetEffA(), and TG4GeometryServices::~TG4GeometryServices().
G4double TG4G3Units::Field () inline static
Return G3 magnetic field unit
Definition at line 108 of file TG4G3Units.h.
Referenced by TG4MagneticField::GetFieldValue(), and TG4CachedMagneticField::GetFieldValue().
Member Data Documentation
const G4double TG4G3Units::fgkLength = cm static private
G3 length unit.
Definition at line 47 of file TG4G3Units.h.
Referenced by Length().
const G4double TG4G3Units::fgkAngle = deg static private
G3 angle unit.
Definition at line 48 of file TG4G3Units.h.
Referenced by Angle().
const G4double TG4G3Units::fgkTime = s static private
G3 time unit.
Definition at line 49 of file TG4G3Units.h.
Referenced by Time().
const G4double TG4G3Units::fgkCharge = eplus static private
G3 charge unit.
Definition at line 50 of file TG4G3Units.h.
Referenced by Charge().
const G4double TG4G3Units::fgkEnergy = GeV static private
G3 energy unit.
Definition at line 51 of file TG4G3Units.h.
Referenced by Energy().
const G4double TG4G3Units::fgkMass = GeV static private
G3 mass unit.
Definition at line 52 of file TG4G3Units.h.
Referenced by Mass().
const G4double TG4G3Units::fgkMassDensity = g / cm3 static private
G3 mass density unit.
Definition at line 53 of file TG4G3Units.h.
Referenced by MassDensity().
const G4double TG4G3Units::fgkAtomicWeight = g / mole static private
G3 atomic weight unit.
Definition at line 54 of file TG4G3Units.h.
Referenced by AtomicWeight().
const G4double TG4G3Units::fgkField = kilogauss static private
G3 magnetic field unit.
Definition at line 55 of file TG4G3Units.h.
Referenced by Field().
The documentation for this class was generated from the following files:
source/global/include/TG4G3Units.h
source/global/src/TG4G3Units.cxx