Geant4 VMC: TG4StackPopper Class Reference
TG4StackPopper Class Reference
physics
The process which pops particles defined by user from the VMC stack and passes them to tracking.
#include <TG4StackPopper.h>
Public Member Functions
TG4StackPopper (const G4String &processName="stackPopper")
virtual ~TG4StackPopper ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
void Notify ()
void Reset ()
void SetMCStack (TVirtualMCStack *mcStack)
void SetDoExclusiveStep (G4TrackStatus trackStatus)
G4bool HasPoppedTracks () const
Static Public Member Functions
static TG4StackPopper * Instance ()
Private Member Functions
TG4StackPopper (const TG4StackPopper &right)
Not implemented.
TG4StackPopper & operator= (const TG4StackPopper &right)
Not implemented.
Private Attributes
TVirtualMCStack * fMCStack
Cached pointer to thread-local VMC stack.
G4int fNofDoneTracks
the counter for popped tracks
G4bool fDoExclusiveStep
G4TrackStatus fTrackStatus
The track status to be restored after performing exclusive step.
Static Private Attributes
static G4ThreadLocal TG4StackPopper * fgInstance = 0
this instance
Detailed Description
The process which pops particles defined by user from the VMC stack and passes them to tracking.
Author
I. Hrivnacova; IPN Orsay
Definition at line 30 of file TG4StackPopper.h.
Constructor & Destructor Documentation
TG4StackPopper::TG4StackPopper (const G4String & processName = "stackPopper")
Standard constructor
Definition at line 30 of file TG4StackPopper.cxx.
Referenced by AtRestDoIt().
TG4StackPopper::~TG4StackPopper () virtual
Destructor
Definition at line 50 of file TG4StackPopper.cxx.
TG4StackPopper::TG4StackPopper (const TG4StackPopper & right) private
Not implemented.
Member Function Documentation
TG4StackPopper * TG4StackPopper::Instance () inline static
Return this instance.
Definition at line 111 of file TG4StackPopper.h.
Referenced by TG4RunManager::CacheMCStack(), TG4TrackManager::LateInitialize(), TG4TrackingAction::LateInitialize(), and TG4SteppingAction::LateInitialize().
G4bool TG4StackPopper::IsApplicable (const G4ParticleDefinition &) inline virtual
Applicable to any particles
Definition at line 117 of file TG4StackPopper.h.
G4double TG4StackPopper::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Do not limit step, set condition to StronglyForced if there are popped tracks in the stack
Definition at line 62 of file TG4StackPopper.cxx.
G4VParticleChange * TG4StackPopper::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Add particles from the stack as secondaries to the current particle
Definition at line 82 of file TG4StackPopper.cxx.
virtual G4double TG4StackPopper::AlongStepGetPhysicalInteractionLength (const G4Track & , G4double , G4double , G4double & , G4GPILSelection *) inline virtual
Definition at line 51 of file TG4StackPopper.h.
virtual G4double TG4StackPopper::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Definition at line 59 of file TG4StackPopper.h.
virtual G4VParticleChange* TG4StackPopper::AlongStepDoIt (const G4Track & , const G4Step &) inline virtual
Definition at line 65 of file TG4StackPopper.h.
virtual G4VParticleChange* TG4StackPopper::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Definition at line 71 of file TG4StackPopper.h.
void TG4StackPopper::Notify ()
Increment the number of done tracks
Definition at line 156 of file TG4StackPopper.cxx.
Referenced by AtRestDoIt(), TG4TrackingAction::PreUserTrackingAction(), and TG4TrackManager::SaveSecondaries().
void TG4StackPopper::Reset ()
Reset the number of done tracks to the number od tracks in stack (when starting track)
Definition at line 164 of file TG4StackPopper.cxx.
Referenced by AtRestDoIt(), and TG4TrackingAction::PreUserTrackingAction().
void TG4StackPopper::SetMCStack (TVirtualMCStack * mcStack) inline
Set cached pointer to thread-local VMC stack
Definition at line 124 of file TG4StackPopper.h.
Referenced by AtRestDoIt(), and TG4RunManager::CacheMCStack().
void TG4StackPopper::SetDoExclusiveStep (G4TrackStatus trackStatus)
Activate performing exclusive step and keep the track status
Definition at line 173 of file TG4StackPopper.cxx.
Referenced by AtRestDoIt(), and TG4SteppingAction::UserSteppingAction().
G4bool TG4StackPopper::HasPoppedTracks () const
Return true if there are user tracks in stack
Definition at line 182 of file TG4StackPopper.cxx.
Referenced by AtRestDoIt(), PostStepGetPhysicalInteractionLength(), and TG4SteppingAction::UserSteppingAction().
TG4StackPopper& TG4StackPopper::operator= (const TG4StackPopper & right) private
Not implemented.
Referenced by AtRestDoIt().
Member Data Documentation
G4ThreadLocal TG4StackPopper * TG4StackPopper::fgInstance = 0 static private
this instance
Definition at line 91 of file TG4StackPopper.h.
Referenced by Instance(), TG4StackPopper(), and ~TG4StackPopper().
TVirtualMCStack* TG4StackPopper::fMCStack private
Cached pointer to thread-local VMC stack.
Definition at line 94 of file TG4StackPopper.h.
Referenced by PostStepDoIt(), Reset(), SetMCStack(), and TG4StackPopper().
G4int TG4StackPopper::fNofDoneTracks private
the counter for popped tracks
Definition at line 97 of file TG4StackPopper.h.
Referenced by HasPoppedTracks(), Notify(), PostStepDoIt(), and Reset().
G4bool TG4StackPopper::fDoExclusiveStep private
The indication for performing exclusive step
It is set in stepping action when a track is not alive and there are user tracks in the VMC stack
Definition at line 103 of file TG4StackPopper.h.
Referenced by PostStepDoIt(), PostStepGetPhysicalInteractionLength(), and SetDoExclusiveStep().
G4TrackStatus TG4StackPopper::fTrackStatus private
The track status to be restored after performing exclusive step.
Definition at line 106 of file TG4StackPopper.h.
Referenced by PostStepDoIt(), and SetDoExclusiveStep().
The documentation for this class was generated from the following files:
source/physics/include/TG4StackPopper.h
source/physics/src/TG4StackPopper.cxx