Geant4 VMC: TG4ProcessControlMap Class Reference
TG4ProcessControlMap Class Reference
global
Maps G4 process names to TG4G3Control.
#include <TG4ProcessControlMap.h>
Public Types
typedef std::map< G4String, TG4G3Control, std::less< G4String > > Map
The map of TG4G3Controls to strings.
typedef Map::iterator MapIterator
The iterator for the map of TG4G3Controls to strings.
typedef Map::const_iterator MapConstIterator
The constant iterator for the map of TG4G3Controls to strings.
Public Member Functions
TG4ProcessControlMap ()
virtual ~TG4ProcessControlMap ()
G4bool Add (G4VProcess *process, TG4G3Control second)
G4bool Add (G4String processName, TG4G3Control second)
void PrintAll () const
void Clear ()
TG4G3Control GetControl (const G4VProcess *process)
TG4G3Control GetControl (const G4String &processName)
const G4String & GetControlName (const G4VProcess *process)
const G4String & GetControlName (const G4String &processName)
Static Public Member Functions
static TG4ProcessControlMap * Instance ()
Private Member Functions
TG4ProcessControlMap (const TG4ProcessControlMap &right)
Not implemented.
TG4ProcessControlMap & operator= (const TG4ProcessControlMap &right)
Not implemented.
G4bool IsDefined (const G4String &processName)
Private Attributes
Map fMap
map container
Static Private Attributes
static TG4ProcessControlMap * fgInstance = 0
this instance
Detailed Description
Maps G4 process names to TG4G3Control.
Singleton map container for associated pairs G4 process name and TG4G3Control.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 33 of file TG4ProcessControlMap.h.
Member Typedef Documentation
typedef std::map<G4String, TG4G3Control, std::less<G4String> > TG4ProcessControlMap::Map
The map of TG4G3Controls to strings.
Definition at line 37 of file TG4ProcessControlMap.h.
typedef Map::iterator TG4ProcessControlMap::MapIterator
The iterator for the map of TG4G3Controls to strings.
Definition at line 40 of file TG4ProcessControlMap.h.
typedef Map::const_iterator TG4ProcessControlMap::MapConstIterator
The constant iterator for the map of TG4G3Controls to strings.
Definition at line 43 of file TG4ProcessControlMap.h.
Constructor & Destructor Documentation
TG4ProcessControlMap::TG4ProcessControlMap ()
Default constructor
Definition at line 26 of file TG4ProcessControlMap.cxx.
TG4ProcessControlMap::~TG4ProcessControlMap () virtual
Destructor
Definition at line 39 of file TG4ProcessControlMap.cxx.
TG4ProcessControlMap::TG4ProcessControlMap (const TG4ProcessControlMap & right) private
Not implemented.
Member Function Documentation
TG4ProcessControlMap * TG4ProcessControlMap::Instance () inline static
Return this instance
Definition at line 82 of file TG4ProcessControlMap.h.
Referenced by TG4ProcessControlMapPhysics::ConstructProcess(), TG4ProcessControlMapPhysics::FillMap(), TG4G3ControlVector::GetControlValue(), and TG4ComposedPhysicsMessenger::SetNewValue().
G4bool TG4ProcessControlMap::Add (G4VProcess * process, TG4G3Control second)
Add the pair to the map.
Definition at line 66 of file TG4ProcessControlMap.cxx.
Referenced by TG4ProcessControlMapPhysics::FillMap().
G4bool TG4ProcessControlMap::Add (G4String processName, TG4G3Control second)
Add the pair to the map.
Definition at line 76 of file TG4ProcessControlMap.cxx.
void TG4ProcessControlMap::PrintAll () const
Dump the whole map.
Definition at line 90 of file TG4ProcessControlMap.cxx.
Referenced by TG4ComposedPhysicsMessenger::SetNewValue().
void TG4ProcessControlMap::Clear ()
Clear the map.
Definition at line 109 of file TG4ProcessControlMap.cxx.
TG4G3Control TG4ProcessControlMap::GetControl (const G4VProcess * process)
Return the G3 process control for the process with a given name.
Definition at line 117 of file TG4ProcessControlMap.cxx.
Referenced by TG4ProcessControlMapPhysics::ConstructProcess(), GetControlName(), and TG4G3ControlVector::GetControlValue().
TG4G3Control TG4ProcessControlMap::GetControl (const G4String & processName)
Return the G3 process control for the process with a given name.
Definition at line 127 of file TG4ProcessControlMap.cxx.
const G4String & TG4ProcessControlMap::GetControlName (const G4VProcess * process)
Return the G3 process control name for the process with a given name.
Definition at line 139 of file TG4ProcessControlMap.cxx.
const G4String & TG4ProcessControlMap::GetControlName (const G4String & processName)
Return the G3 process control name for the process with a given name.
Definition at line 149 of file TG4ProcessControlMap.cxx.
TG4ProcessControlMap& TG4ProcessControlMap::operator= (const TG4ProcessControlMap & right) private
Not implemented.
G4bool TG4ProcessControlMap::IsDefined (const G4String & processName) private
Return true if the first is already in the map.
Definition at line 51 of file TG4ProcessControlMap.cxx.
Referenced by Add().
Member Data Documentation
TG4ProcessControlMap * TG4ProcessControlMap::fgInstance = 0 static private
this instance
Definition at line 74 of file TG4ProcessControlMap.h.
Referenced by Instance(), TG4ProcessControlMap(), and ~TG4ProcessControlMap().
Map TG4ProcessControlMap::fMap private
map container
Definition at line 77 of file TG4ProcessControlMap.h.
Referenced by Add(), Clear(), GetControl(), IsDefined(), and PrintAll().
The documentation for this class was generated from the following files:
source/global/include/TG4ProcessControlMap.h
source/global/src/TG4ProcessControlMap.cxx