Geant4 VMC: TG4TrackManager Class Reference
TG4TrackManager Class Reference
event
The class for storing G4 tracks in VMC sack.
#include <TG4TrackManager.h>
Public Member Functions
TG4TrackManager ()
virtual ~TG4TrackManager ()
void LateInitialize ()
void AddPrimaryParticleId (G4int id)
G4int SetTrackInformation (const G4Track *aTrack, G4bool overWrite=false)
void SetParentToTrackInformation (const G4Track *aTrack)
void SetBackPDGLifetime (const G4Track *aTrack)
void TrackToStack (const G4Track *track, G4bool overWrite=false)
void PrimaryToStack (const G4PrimaryVertex *vertex, const G4PrimaryParticle *particle)
void SaveSecondaries (const G4Track *track, const G4TrackVector *secondaries)
void SetMCStack (TVirtualMCStack *mcStack)
void SetTrackSaveControl (TG4TrackSaveControl control)
void SetSaveDynamicCharge (G4bool saveDynamicCharge)
void SetNofTracks (G4int nofTracks)
void SetG4TrackingManager (G4TrackingManager *trackingManager)
void ResetPrimaryParticleIds ()
TG4TrackInformation * GetTrackInformation (const G4Track *track) const
TG4TrackSaveControl GetTrackSaveControl () const
G4bool GetSaveDynamicCharge () const
G4int GetNofTracks () const
G4bool IsUserTrack (const G4Track *track) const
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Static Public Member Functions
static TG4TrackManager * Instance ()
Private Member Functions
TG4TrackManager (const TG4TrackManager &right)
Not implemented.
TG4TrackManager & operator= (const TG4TrackManager &right)
Not implemented.
Private Attributes
G4TrackingManager * fG4TrackingManager
G4 tracking manager.
std::vector< G4int > fPrimaryParticleIds
The VMC stack primary particle Ids.
TG4TrackSaveControl fTrackSaveControl
control of saving secondaries
TVirtualMCStack * fMCStack
Cached pointer to thread-local VMC stack.
TG4StackPopper * fStackPopper
Cached pointer to thread-local stack popper.
G4bool fSaveDynamicCharge
control of saving dynamic charge of secondaries
G4int fTrackCounter
tracks counter
G4int fCurrentTrackID
current track ID
G4int fNofSavedSecondaries
number of secondaries already saved
Static Private Attributes
static G4ThreadLocal TG4TrackManager * fgInstance = 0
this instance
Detailed Description
The class for storing G4 tracks in VMC sack.
It provides methods for storing G4 primary particles and secondary tracks and utility functions for updating TG4TrackInformation, which hold the info about correspondence between Geant4 and VMC stack numbering
Author
I. Hrivnacova; IPN, Orsay
Definition at line 43 of file TG4TrackManager.h.
Constructor & Destructor Documentation
TG4TrackManager::TG4TrackManager ()
Default constructor
Definition at line 40 of file TG4TrackManager.cxx.
TG4TrackManager::~TG4TrackManager () virtual
Destructor
Definition at line 62 of file TG4TrackManager.cxx.
TG4TrackManager::TG4TrackManager (const TG4TrackManager & right) private
Not implemented.
Member Function Documentation
TG4TrackManager * TG4TrackManager::Instance () inline static
Return this instance.
Definition at line 110 of file TG4TrackManager.h.
Referenced by TG4RunManager::CacheMCStack(), TG4EventAction::LateInitialize(), TG4SteppingAction::LateInitialize(), TG4StepManager::LateInitialize(), TG4TrackingActionMessenger::SetNewValue(), and TG4PrimaryGeneratorAction::TransformPrimaries().
void TG4TrackManager::LateInitialize ()
Cache thread-local pointers
Definition at line 74 of file TG4TrackManager.cxx.
Referenced by TG4TrackingAction::LateInitialize().
void TG4TrackManager::AddPrimaryParticleId (G4int id)
Puts the given id in fPrimaryParticleIds. This is then used to keep the primary track Ids identical with Ids in VMC stack.
Definition at line 82 of file TG4TrackManager.cxx.
Referenced by TG4PrimaryGeneratorAction::TransformPrimaries().
G4int TG4TrackManager::SetTrackInformation (const G4Track * aTrack, G4bool overWrite = false)
Set track index in VMC stack to track information and return its value
Definition at line 92 of file TG4TrackManager.cxx.
Referenced by TG4TrackingAction::PreUserTrackingAction(), and SaveSecondaries().
void TG4TrackManager::SetParentToTrackInformation (const G4Track * aTrack)
Set parent track particle index to the secondary tracks.
Definition at line 153 of file TG4TrackManager.cxx.
Referenced by TG4TrackingAction::PostUserTrackingAction(), TG4SteppingAction::ProcessTrackIfBelowCut(), and SaveSecondaries().
void TG4TrackManager::SetBackPDGLifetime (const G4Track * aTrack)
Set back the PDG lifetime to the G4ParticleDefinition, if it has been modified by user
Definition at line 200 of file TG4TrackManager.cxx.
Referenced by TG4TrackingAction::PostUserTrackingAction().
void TG4TrackManager::TrackToStack (const G4Track * track, G4bool overWrite = false)
Get all needed parameters from G4track and pass them to the VMC stack.
Definition at line 219 of file TG4TrackManager.cxx.
Referenced by TG4TrackingAction::PreUserTrackingAction(), SaveSecondaries(), and SetBackPDGLifetime().
void TG4TrackManager::PrimaryToStack (const G4PrimaryVertex * vertex, const G4PrimaryParticle * particle)
Add primary particle to VMC stack
Definition at line 298 of file TG4TrackManager.cxx.
Referenced by TG4EventAction::BeginOfEventAction().
void TG4TrackManager::SaveSecondaries (const G4Track * track, const G4TrackVector * secondaries)
Save the secondary particles on VMC stack
Definition at line 353 of file TG4TrackManager.cxx.
Referenced by TG4SteppingAction::UserSteppingAction().
void TG4TrackManager::SetMCStack (TVirtualMCStack * mcStack) inline
Set cached pointer to thread-local VMC stack
Definition at line 116 of file TG4TrackManager.h.
Referenced by TG4RunManager::CacheMCStack().
void TG4TrackManager::SetTrackSaveControl (TG4TrackSaveControl control) inline
Set control for saving secondaries in the VMC stack
Definition at line 122 of file TG4TrackManager.h.
Referenced by TG4ActionInitialization::Build(), and TG4TrackingActionMessenger::SetNewValue().
void TG4TrackManager::SetSaveDynamicCharge (G4bool saveDynamicCharge) inline
Set control of saving dynamic charge of secondaries (in TParticle::fStatus)
Definition at line 128 of file TG4TrackManager.h.
Referenced by TG4ActionInitialization::Build(), and TG4TrackingActionMessenger::SetNewValue().
void TG4TrackManager::SetNofTracks (G4int nofTracks) inline
Set number of tracks
Definition at line 135 of file TG4TrackManager.h.
Referenced by TG4TrackingAction::PrepareNewEvent().
void TG4TrackManager::SetG4TrackingManager (G4TrackingManager * trackingManager) inline
Set G4 tracking manager
Definition at line 141 of file TG4TrackManager.h.
Referenced by TG4TrackingAction::PrepareNewEvent().
void TG4TrackManager::ResetPrimaryParticleIds ()
Clear the vector with the VMC stack primary particle Ids
Definition at line 391 of file TG4TrackManager.cxx.
Referenced by TG4PrimaryGeneratorAction::TransformPrimaries().
TG4TrackInformation * TG4TrackManager::GetTrackInformation (const G4Track * track) const
Return user track information.
Definition at line 399 of file TG4TrackManager.cxx.
Referenced by TG4StepManager::ForceDecayTime(), IsUserTrack(), TG4VSpecialCuts::PostStepGetPhysicalInteractionLength(), TG4SteppingAction::ProcessTrackIfBelowCut(), SaveSecondaries(), SetBackPDGLifetime(), SetParentToTrackInformation(), SetTrackInformation(), TG4StepManager::TrackPid(), and TrackToStack().
TG4TrackSaveControl TG4TrackManager::GetTrackSaveControl () const inline
Return control of saving secondaries
Definition at line 148 of file TG4TrackManager.h.
Referenced by TG4ActionInitialization::Build(), TG4TrackingAction::PrepareNewEvent(), TG4TrackingAction::PreUserTrackingAction(), and TG4SteppingAction::UserSteppingAction().
G4bool TG4TrackManager::GetSaveDynamicCharge () const inline
Return the control of saving dynamic charge of secondaries
Definition at line 154 of file TG4TrackManager.h.
Referenced by TG4ActionInitialization::Build().
G4int TG4TrackManager::GetNofTracks () const inline
Return track counter = current number of tracks (in event)
Definition at line 160 of file TG4TrackManager.h.
Referenced by TG4EventAction::EndOfEventAction().
G4bool TG4TrackManager::IsUserTrack (const G4Track * track) const
Return true if the secondary track was defined by user
Definition at line 424 of file TG4TrackManager.cxx.
Referenced by TG4TrackingAction::PreUserTrackingAction().
TG4TrackManager& TG4TrackManager::operator= (const TG4TrackManager & right) private
Not implemented.
Member Data Documentation
G4ThreadLocal TG4TrackManager * TG4TrackManager::fgInstance = 0 static private
this instance
Definition at line 87 of file TG4TrackManager.h.
Referenced by Instance(), TG4TrackManager(), and ~TG4TrackManager().
G4TrackingManager* TG4TrackManager::fG4TrackingManager private
G4 tracking manager.
Definition at line 90 of file TG4TrackManager.h.
Referenced by SetG4TrackingManager(), SetParentToTrackInformation(), and SetTrackInformation().
std::vector<G4int> TG4TrackManager::fPrimaryParticleIds private
The VMC stack primary particle Ids.
Definition at line 92 of file TG4TrackManager.h.
Referenced by AddPrimaryParticleId(), ResetPrimaryParticleIds(), and SetTrackInformation().
TG4TrackSaveControl TG4TrackManager::fTrackSaveControl private
control of saving secondaries
Definition at line 93 of file TG4TrackManager.h.
Referenced by GetTrackSaveControl(), SetTrackInformation(), and SetTrackSaveControl().
TVirtualMCStack* TG4TrackManager::fMCStack private
Cached pointer to thread-local VMC stack.
Definition at line 96 of file TG4TrackManager.h.
Referenced by PrimaryToStack(), SetMCStack(), SetTrackInformation(), and TrackToStack().
TG4StackPopper* TG4TrackManager::fStackPopper private
Cached pointer to thread-local stack popper.
Definition at line 99 of file TG4TrackManager.h.
Referenced by LateInitialize(), and SaveSecondaries().
G4bool TG4TrackManager::fSaveDynamicCharge private
control of saving dynamic charge of secondaries
Definition at line 102 of file TG4TrackManager.h.
Referenced by GetSaveDynamicCharge(), PrimaryToStack(), SetSaveDynamicCharge(), and TrackToStack().
G4int TG4TrackManager::fTrackCounter private
tracks counter
Definition at line 103 of file TG4TrackManager.h.
Referenced by GetNofTracks(), SetNofTracks(), and SetTrackInformation().
G4int TG4TrackManager::fCurrentTrackID private
current track ID
Definition at line 104 of file TG4TrackManager.h.
Referenced by SaveSecondaries().
G4int TG4TrackManager::fNofSavedSecondaries private
number of secondaries already saved
Definition at line 105 of file TG4TrackManager.h.
Referenced by SaveSecondaries(), and SetParentToTrackInformation().
The documentation for this class was generated from the following files:
source/event/include/TG4TrackManager.h
source/event/src/TG4TrackManager.cxx