Geant4 VMC: TG4G3CutVector Class Reference
TG4G3CutVector Class Reference
global
Vector of kinetic energy cut values with convenient set/get methods.
#include <TG4G3CutVector.h>
Public Member Functions
TG4G3CutVector ()
TG4G3CutVector (const TG4G3CutVector &right)
virtual ~TG4G3CutVector ()
TG4G3CutVector & operator= (const TG4G3CutVector &right)
G4double operator[] (G4int index) const
void SetCut (TG4G3Cut cut, G4double cutValue)
void SetG3Defaults ()
G4bool Update (const TG4G3CutVector &vector)
void SetDeltaRaysOn (G4bool value)
G4String Format () const
void Print () const
G4double GetMinEkineForGamma (const G4Track &track) const
G4double GetMinEkineForElectron (const G4Track &track) const
G4double GetMinEkineForEplus (const G4Track &track) const
G4double GetMinEkineForChargedHadron (const G4Track &track) const
G4double GetMinEkineForNeutralHadron (const G4Track &track) const
G4double GetMinEkineForMuon (const G4Track &track) const
G4double GetMinEkineForOther (const G4Track &track) const
G4double GetMinEtotPair () const
G4bool IsCut () const
Static Public Member Functions
static G4double Tolerance ()
static TG4G3Cut GetCut (const G4String &cutName)
static G4bool CheckCutValue (TG4G3Cut cut, G4double value)
static const G4String & GetCutName (TG4G3Cut cut)
Static Private Member Functions
static void FillCutNameVector ()
Private Attributes
TG4doubleVector fCutVector
vector of kinetic energy cut values
G4bool fDeltaRaysOn
delta rays process control
Static Private Attributes
static const G4double fgkDCUTEOff = 10. * TeV
cut for delta rays by e- (if off)
static const G4double fgkDCUTMOff = 10. * TeV
cut for delta rays by mu (if off)
static const G4double fgkTolerance = 1. * keV
tolerance for comparing cuts
static TG4StringVector fgCutNameVector
vector of cut parameters names
Detailed Description
Vector of kinetic energy cut values with convenient set/get methods.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 29 of file TG4G3CutVector.h.
Constructor & Destructor Documentation
TG4G3CutVector::TG4G3CutVector ()
Default constructor
Definition at line 117 of file TG4G3CutVector.cxx.
TG4G3CutVector::TG4G3CutVector (const TG4G3CutVector & right)
Copy constructor
Definition at line 130 of file TG4G3CutVector.cxx.
TG4G3CutVector::~TG4G3CutVector () virtual
Destructor
Definition at line 140 of file TG4G3CutVector.cxx.
Member Function Documentation
TG4G3CutVector & TG4G3CutVector::operator= (const TG4G3CutVector & right)
Assignment operator
Definition at line 150 of file TG4G3CutVector.cxx.
G4double TG4G3CutVector::operator[] (G4int index) const
Element access operator
Definition at line 166 of file TG4G3CutVector.cxx.
G4double TG4G3CutVector::Tolerance () inline static
Return tolerance for comparing cuts
Definition at line 98 of file TG4G3CutVector.h.
Referenced by CheckCutValue(), TG4G3PhysicsManager::CheckCutWithTheVector(), and TG4G3Defaults::IsDefaultCut().
TG4G3Cut TG4G3CutVector::GetCut (const G4String & cutName) static
Retrieve corresponding TG4G3Cut constant from the cutName.
Definition at line 43 of file TG4G3CutVector.cxx.
Referenced by TG4G3PhysicsManager::CheckCutWithTheVector(), TG4GeometryServices::PrintCuts(), and TG4PhysicsManager::SetCut().
G4bool TG4G3CutVector::CheckCutValue (TG4G3Cut cut, G4double value) static
Check if the cut value is valid for given cut; if not return false. Currently only the PPCUTM value is tested if it is > 2 * mass of electron.
Definition at line 74 of file TG4G3CutVector.cxx.
Referenced by TG4G3PhysicsManager::CheckCutWithTheVector(), and TG4G3PhysicsManager::SetCut().
const G4String & TG4G3CutVector::GetCutName (TG4G3Cut cut) static
Return name of a specified cut.
Definition at line 102 of file TG4G3CutVector.cxx.
void TG4G3CutVector::SetCut (TG4G3Cut cut, G4double cutValue)
Set the cutValue for the specified cut.
Definition at line 207 of file TG4G3CutVector.cxx.
Referenced by TG4G3PhysicsManager::SetCut(), TG4Limits::SetG3Cut(), and TG4G3Defaults::TG4G3Defaults().
void TG4G3CutVector::SetG3Defaults ()
Set G3 default values for all cuts.
Definition at line 219 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::SetG3DefaultCuts(), and TG4G3PhysicsManager::SetG3DefaultCuts().
G4bool TG4G3CutVector::Update (const TG4G3CutVector & vector)
Update only those values that have not yet been set (=0.) with given vector. Return true if some value was modified.
Definition at line 228 of file TG4G3CutVector.cxx.
void TG4G3CutVector::SetDeltaRaysOn (G4bool value) inline
Return delta rays process control
Definition at line 104 of file TG4G3CutVector.h.
Referenced by TG4G3ControlVector::SetControl().
G4String TG4G3CutVector::Format () const
Format the output into a string.
Definition at line 246 of file TG4G3CutVector.cxx.
Referenced by Print().
void TG4G3CutVector::Print () const
Print the cuts.
Definition at line 283 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::Print(), and TG4ComposedPhysicsMessenger::SetNewValue().
G4double TG4G3CutVector::GetMinEkineForGamma (const G4Track & track) const
Return the cut value for gamma:
BCUTE - if gamma is produced by e- Bremstrahlung
BCUTM - if gamma is produced by muon or hadron Bremstrahlung
CUTGAM - in all other cases
Cut is not applied for "opticalphoton" which is treated in G4 as a particle different from "gamma".
Definition at line 291 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::GetMinEkineForGamma().
G4double TG4G3CutVector::GetMinEkineForElectron (const G4Track & track) const
Return the cut value for e-:
DCUTE - if e- is produced by e- ionisation and DRAY process is selected (default)
DCUTM - if e- is produced by muon ionisation and DRAY process is selected (default)
10 TeV - if e- is produced by ionisation and DRAY process is switched off
CUTELE - in all other cases. The delta ray cuts are applied only in the track first step.
Definition at line 325 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::GetMinEkineForElectron().
G4double TG4G3CutVector::GetMinEkineForEplus (const G4Track & track) const
Return the cut value for e+.
No special cut is applied to e+; the PPCUTM cut is applied on total energy of the e+e- pair.
Definition at line 377 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::GetMinEkineForEplus().
G4double TG4G3CutVector::GetMinEkineForChargedHadron (const G4Track & track) const
Return the cut value for charged hadron (CUTHAD).
Definition at line 387 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::GetMinEkineForChargedHadron().
G4double TG4G3CutVector::GetMinEkineForNeutralHadron (const G4Track & track) const
Return the cut value for neutral hadron (CUTNEU).
Definition at line 396 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::GetMinEkineForNeutralHadron().
G4double TG4G3CutVector::GetMinEkineForMuon (const G4Track & track) const
Return the cut value for muon (CUTMUO)
Definition at line 405 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::GetMinEkineForMuon().
G4double TG4G3CutVector::GetMinEkineForOther (const G4Track & track) const
No cut is applied for other particles.
Definition at line 413 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::GetMinEkineForOther().
G4double TG4G3CutVector::GetMinEtotPair () const
Return the cut value for the pair production by muons (PPCUTM).
Definition at line 421 of file TG4G3CutVector.cxx.
Referenced by TG4SteppingAction::ProcessTrackIfBelowCut().
G4bool TG4G3CutVector::IsCut () const
Return true if any of cuts is set.
Definition at line 429 of file TG4G3CutVector.cxx.
Referenced by TG4Limits::Initialize().
void TG4G3CutVector::FillCutNameVector () static private
Define fCutNameVector.
Definition at line 184 of file TG4G3CutVector.cxx.
Referenced by GetCutName(), and TG4G3CutVector().
Member Data Documentation
const G4double TG4G3CutVector::fgkDCUTEOff = 10. * TeV static private
cut for delta rays by e- (if off)
Definition at line 75 of file TG4G3CutVector.h.
Referenced by Format(), and GetMinEkineForElectron().
const G4double TG4G3CutVector::fgkDCUTMOff = 10. * TeV static private
cut for delta rays by mu (if off)
Definition at line 78 of file TG4G3CutVector.h.
Referenced by Format(), and GetMinEkineForElectron().
const G4double TG4G3CutVector::fgkTolerance = 1. * keV static private
tolerance for comparing cuts
Definition at line 81 of file TG4G3CutVector.h.
Referenced by IsCut(), Tolerance(), and Update().
TG4StringVector TG4G3CutVector::fgCutNameVector static private
vector of cut parameters names
Definition at line 84 of file TG4G3CutVector.h.
Referenced by FillCutNameVector(), Format(), GetCut(), GetCutName(), and TG4G3CutVector().
TG4doubleVector TG4G3CutVector::fCutVector private
vector of kinetic energy cut values
Definition at line 90 of file TG4G3CutVector.h.
Referenced by Format(), GetMinEkineForChargedHadron(), GetMinEkineForElectron(), GetMinEkineForGamma(), GetMinEkineForMuon(), GetMinEkineForNeutralHadron(), GetMinEtotPair(), IsCut(), operator=(), operator[](), SetCut(), SetG3Defaults(), TG4G3CutVector(), and Update().
G4bool TG4G3CutVector::fDeltaRaysOn private
delta rays process control
Definition at line 93 of file TG4G3CutVector.h.
Referenced by Format(), GetMinEkineForElectron(), operator=(), and SetDeltaRaysOn().
The documentation for this class was generated from the following files:
source/global/include/TG4G3CutVector.h
source/global/src/TG4G3CutVector.cxx