Geant4 VMC: TG4SDManager Class Reference
TG4SDManager Class Reference
digits_hits
Geant4 implementation of the TVirtualMC interface methods for access to Geant4 geometry related with sensitive detectors.
#include <TG4SDManager.h>
Public Member Functions
TG4SDManager ()
virtual ~TG4SDManager ()
void Initialize ()
Int_t VolId (const Text_t *volName) const
const char * VolName (Int_t id) const
Int_t NofVolumes () const
Int_t NofVolDaughters (const char *volName) const
const char * VolDaughterName (const char *volName, Int_t i) const
Int_t VolDaughterCopyNo (const char *volName, Int_t i) const
Int_t VolId2Mate (Int_t volumeId) const
void SetSensitiveDetector (const TString &volName, TVirtualMCSensitiveDetector *sd)
TVirtualMCSensitiveDetector * GetSensitiveDetector (const TString &volName) const
void SetExclusiveSDScoring (Bool_t exclusiveSDScoring)
TG4SDConstruction * GetSDConstruction () const
Static Public Member Functions
static TG4SDManager * Instance ()
Private Member Functions
TG4SDManager (const TG4SDManager &right)
Not implemented.
TG4SDManager & operator= (const TG4SDManager &right)
Not implemented.
Private Attributes
TG4SDConstruction * fSDConstruction
sensitive detectors construction
TG4SDServices * fSDServices
services related with sensitive detectors
G4String fNameBuffer
buffer for volume name
Static Private Attributes
static TG4SDManager * fgInstance = 0
this instance
Detailed Description
Geant4 implementation of the TVirtualMC interface methods for access to Geant4 geometry related with sensitive detectors.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 33 of file TG4SDManager.h.
Constructor & Destructor Documentation
TG4SDManager::TG4SDManager ()
Default constructor
Definition at line 28 of file TG4SDManager.cxx.
TG4SDManager::~TG4SDManager () virtual
Destructor
Definition at line 44 of file TG4SDManager.cxx.
TG4SDManager::TG4SDManager (const TG4SDManager & right) private
Not implemented.
Member Function Documentation
TG4SDManager * TG4SDManager::Instance () inline static
Return this instance
Definition at line 87 of file TG4SDManager.h.
Referenced by TG4GeometryManager::ConstructSDandField().
void TG4SDManager::Initialize ()
Create sensitive detectors, sets second indexes for materials (corresponding to G3 tracking media) and clear remaing G3 tables.
Definition at line 59 of file TG4SDManager.cxx.
Referenced by TG4GeometryManager::ConstructSDandField().
Int_t TG4SDManager::VolId (const Text_t * volName) const
Return the volume ID = sensitive detector identifier.
Definition at line 71 of file TG4SDManager.cxx.
Referenced by TGeant4::VolId().
const char * TG4SDManager::VolName (Int_t id) const
Return the name of the volume specified by volume ID (= sensitive detector name)
Definition at line 79 of file TG4SDManager.cxx.
Referenced by TGeant4::VolName().
Int_t TG4SDManager::NofVolumes () const
Return the total number of VMC volumes (= number of sensitive detectors).
Definition at line 89 of file TG4SDManager.cxx.
Referenced by TGeant4::NofVolumes().
Int_t TG4SDManager::NofVolDaughters (const char * volName) const
Return the number of daughters of the volume specified by name
Definition at line 98 of file TG4SDManager.cxx.
Referenced by TGeant4::NofVolDaughters().
const char * TG4SDManager::VolDaughterName (const char * volName, Int_t i) const
Return the name of the i-th daughter of the volume specified by name.
Definition at line 106 of file TG4SDManager.cxx.
Referenced by TGeant4::VolDaughterName().
Int_t TG4SDManager::VolDaughterCopyNo (const char * volName, Int_t i) const
Return the copyNo of the i-th daughter of the volume specified by name.
Definition at line 114 of file TG4SDManager.cxx.
Referenced by TGeant4::VolDaughterCopyNo().
Int_t TG4SDManager::VolId2Mate (Int_t volumeId) const
Return the material number for a given volume Id
Definition at line 122 of file TG4SDManager.cxx.
Referenced by TGeant4::VolId2Mate().
void TG4SDManager::SetSensitiveDetector (const TString & volName, TVirtualMCSensitiveDetector * sd)
Set user sensitive detector to (a) volume(s) with the given name
Definition at line 130 of file TG4SDManager.cxx.
Referenced by TGeant4::SetSensitiveDetector().
TVirtualMCSensitiveDetector * TG4SDManager::GetSensitiveDetector (const TString & volName) const
Return the user sensitive detector for a volume with the given name
Definition at line 139 of file TG4SDManager.cxx.
Referenced by TGeant4::GetSensitiveDetector().
void TG4SDManager::SetExclusiveSDScoring (Bool_t exclusiveSDScoring)
Set scoring option
Definition at line 148 of file TG4SDManager.cxx.
Referenced by TGeant4::SetExclusiveSDScoring().
TG4SDConstruction * TG4SDManager::GetSDConstruction () const inline
Return sensitive detctor construction
Definition at line 93 of file TG4SDManager.h.
TG4SDManager& TG4SDManager::operator= (const TG4SDManager & right) private
Not implemented.
Member Data Documentation
TG4SDManager * TG4SDManager::fgInstance = 0 static private
this instance
Definition at line 70 of file TG4SDManager.h.
Referenced by Instance(), TG4SDManager(), and ~TG4SDManager().
TG4SDConstruction* TG4SDManager::fSDConstruction private
sensitive detectors construction
Definition at line 76 of file TG4SDManager.h.
Referenced by GetSDConstruction(), Initialize(), SetExclusiveSDScoring(), TG4SDManager(), and ~TG4SDManager().
TG4SDServices* TG4SDManager::fSDServices private
services related with sensitive detectors
Definition at line 79 of file TG4SDManager.h.
Referenced by GetSensitiveDetector(), NofVolDaughters(), NofVolumes(), SetSensitiveDetector(), TG4SDManager(), VolDaughterCopyNo(), VolDaughterName(), VolId(), VolId2Mate(), VolName(), and ~TG4SDManager().
G4String TG4SDManager::fNameBuffer mutable private
buffer for volume name
Definition at line 82 of file TG4SDManager.h.
Referenced by VolName().
The documentation for this class was generated from the following files:
source/digits+hits/include/TG4SDManager.h
source/digits+hits/src/TG4SDManager.cxx