Geant4 VMC: TG4RunConfiguration Class Reference
TG4RunConfiguration Class Reference
run
Takes care of creating Geant4 user action classes using VMC.
#include <TG4RunConfiguration.h>
Public Member Functions
TG4RunConfiguration (const TString &userGeometry, const TString &physicsList="emStandard", const TString &specialProcess="stepLimiter", Bool_t specialStacking=false, Bool_t mtApplication=true)
virtual ~TG4RunConfiguration ()
virtual G4VUserDetectorConstruction * CreateDetectorConstruction ()
virtual G4VUserPhysicsList * CreatePhysicsList ()
virtual G4VUserPrimaryGeneratorAction * CreatePrimaryGenerator ()
virtual G4UserRunAction * CreateRunAction ()
virtual G4UserEventAction * CreateEventAction ()
virtual TG4TrackingAction * CreateTrackingAction ()
virtual TG4SteppingAction * CreateSteppingAction ()
virtual G4UserStackingAction * CreateStackingAction ()
virtual TG4VUserRegionConstruction * CreateUserRegionConstruction ()
virtual TG4VUserPostDetConstruction * CreateUserPostDetConstruction ()
virtual TG4VUserFastSimulation * CreateUserFastSimulation ()
void SetMTApplication (Bool_t mtApplication)
void SetParameter (const TString &name, Double_t value)
TString GetUserGeometry () const
TString GetPhysicsListSelection () const
Bool_t IsSpecialStacking () const
Bool_t IsSpecialControls () const
Bool_t IsSpecialCuts () const
Bool_t IsMTApplication () const
Protected Attributes
TString fUserGeometry
way of building geometry
TString fPhysicsListSelection
physics list selection
TString fSpecialProcessSelection
special process selection
Bool_t fSpecialStacking
option for special stacking
Bool_t fMTApplication
option for MT mode if available
Bool_t fSpecialControls
option for special controls
Bool_t fSpecialCuts
option for special cuts
G4UImessenger * fAGDDMessenger
XML messenger.
G4UImessenger * fGDMLMessenger
XML messenger.
std::map< TString, Double_t > fParameters
Private Member Functions
TG4RunConfiguration ()
Not implemented.
TG4RunConfiguration (const TG4RunConfiguration &right)
Not implemented.
TG4RunConfiguration & operator= (const TG4RunConfiguration &right)
Not implemented.
Detailed Description
Takes care of creating Geant4 user action classes using VMC.
This class takes care of creating all Geant4 user defined mandatory and action classes that will be initialized and managed by Geant4 kernel (G4RunManager).
The class can be extended in a user application by inheritence; this gives a user possibility to extend each Geant4 user defined class.
In constructor user has to specify the geometry input and select geometry navigation via the following options:
geomVMCtoGeant4 - geometry defined via VMC, G4 native navigation
geomVMCtoRoot - geometry defined via VMC, Root navigation
geomRoot - geometry defined via Root, Root navigation
geomRootToGeant4 - geometry defined via Root, G4 native navigation
geomGeant4 - geometry defined via Geant4, G4 native navigation
The second argument in the constructor selects physics list:
emStandard - standard em physics (default)
emStandard+optical - standard em physics + optical physics
XYZ - selected hadron physics list (XYZ = LHEP, QGSP, ...)
XYZ+optical - selected hadron physics list + optical physics
The third argument activates the special processes in the TG4SpecialPhysicsList, which implement VMC features:
stepLimiter - step limiter (default)
specialCuts - VMC cuts
specialControls - VMC controls for activation/inactivation selected processes
stackPopper - stackPopper process When more than one options are selected, they should be separated with '+' character: eg. stepLimit+specialCuts.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 76 of file TG4RunConfiguration.h.
Constructor & Destructor Documentation
TG4RunConfiguration::TG4RunConfiguration (const TString & userGeometry, const TString & physicsList = "emStandard", const TString & specialProcess = "stepLimiter", Bool_t specialStacking = false, Bool_t mtApplication = true)
Standard constructor
Definition at line 41 of file TG4RunConfiguration.cxx.
TG4RunConfiguration::~TG4RunConfiguration () virtual
Destructor
Definition at line 126 of file TG4RunConfiguration.cxx.
TG4RunConfiguration::TG4RunConfiguration () private
Not implemented.
TG4RunConfiguration::TG4RunConfiguration (const TG4RunConfiguration & right) private
Not implemented.
Member Function Documentation
G4VUserDetectorConstruction * TG4RunConfiguration::CreateDetectorConstruction () virtual
Create and return Geant4 VMC default detector construction
Definition at line 139 of file TG4RunConfiguration.cxx.
Referenced by TG4RunManager::ConfigureRunManager().
G4VUserPhysicsList * TG4RunConfiguration::CreatePhysicsList () virtual
Create default Geant4 VMC physics list
Definition at line 149 of file TG4RunConfiguration.cxx.
Referenced by TG4RunManager::ConfigureRunManager().
G4VUserPrimaryGeneratorAction * TG4RunConfiguration::CreatePrimaryGenerator () virtual
Create and return Geant4 VMC default primary generator
Definition at line 222 of file TG4RunConfiguration.cxx.
Referenced by TG4ActionInitialization::Build().
G4UserRunAction * TG4RunConfiguration::CreateRunAction () virtual
Create and return Geant4 VMC default run action
Definition at line 230 of file TG4RunConfiguration.cxx.
Referenced by TG4ActionInitialization::Build(), and TG4ActionInitialization::BuildForMaster().
G4UserEventAction * TG4RunConfiguration::CreateEventAction () virtual
Create and return Geant4 VMC default event action
Definition at line 238 of file TG4RunConfiguration.cxx.
Referenced by TG4ActionInitialization::Build(), and TG4ActionInitialization::TG4ActionInitialization().
TG4TrackingAction * TG4RunConfiguration::CreateTrackingAction () virtual
Create and return Geant4 VMC default tracking action
Definition at line 246 of file TG4RunConfiguration.cxx.
Referenced by TG4ActionInitialization::Build(), and TG4ActionInitialization::TG4ActionInitialization().
TG4SteppingAction * TG4RunConfiguration::CreateSteppingAction () virtual
Create and return Geant4 VMC default stepping action
Definition at line 254 of file TG4RunConfiguration.cxx.
Referenced by TG4ActionInitialization::Build(), and TG4ActionInitialization::TG4ActionInitialization().
G4UserStackingAction * TG4RunConfiguration::CreateStackingAction () virtual
Create and return Geant4 VMC special stacking action
Definition at line 262 of file TG4RunConfiguration.cxx.
Referenced by TG4ActionInitialization::Build(), and TG4ActionInitialization::TG4ActionInitialization().
TG4VUserRegionConstruction * TG4RunConfiguration::CreateUserRegionConstruction () virtual
No region construction is defined by default
Definition at line 272 of file TG4RunConfiguration.cxx.
Referenced by TG4RunManager::ConfigureRunManager().
TG4VUserPostDetConstruction * TG4RunConfiguration::CreateUserPostDetConstruction () virtual
No user post detector construction is defined by default
Definition at line 281 of file TG4RunConfiguration.cxx.
Referenced by TG4RunManager::ConfigureRunManager().
TG4VUserFastSimulation * TG4RunConfiguration::CreateUserFastSimulation () virtual
No user fast simulation is defined by default
Definition at line 289 of file TG4RunConfiguration.cxx.
Referenced by TG4RunManager::ConfigureRunManager().
void TG4RunConfiguration::SetMTApplication (Bool_t mtApplication)
Select running application in MT mode, if available.
Definition at line 297 of file TG4RunConfiguration.cxx.
void TG4RunConfiguration::SetParameter (const TString & name, Double_t value)
Set a special paremeter which can be then used later. Actually used for monopole properties: monopoleMass, monopoleElCharge, monopoleMagCharge
Definition at line 305 of file TG4RunConfiguration.cxx.
TString TG4RunConfiguration::GetUserGeometry () const
Return the way user geometry is built
Definition at line 322 of file TG4RunConfiguration.cxx.
Referenced by TG4RunManager::CloneRootNavigatorForWorker(), and TG4RunManager::ConfigureRunManager().
TString TG4RunConfiguration::GetPhysicsListSelection () const inline
Return physics list selection
Definition at line 141 of file TG4RunConfiguration.h.
Referenced by TGeant4::TGeant4().
Bool_t TG4RunConfiguration::IsSpecialStacking () const
Return true if special stacking is activated
Definition at line 334 of file TG4RunConfiguration.cxx.
Bool_t TG4RunConfiguration::IsSpecialControls () const
Return true if special controls are activated
Definition at line 342 of file TG4RunConfiguration.cxx.
Referenced by TG4ActionInitialization::Build().
Bool_t TG4RunConfiguration::IsSpecialCuts () const
Return true if special controls are activated
Definition at line 350 of file TG4RunConfiguration.cxx.
Referenced by TG4RunManager::LateInitialize().
Bool_t TG4RunConfiguration::IsMTApplication () const
Return true if running in multi-threading mode is activated
Definition at line 358 of file TG4RunConfiguration.cxx.
Referenced by TG4RunManager::ConfigureRunManager(), and TG4ActionInitialization::~TG4ActionInitialization().
TG4RunConfiguration& TG4RunConfiguration::operator= (const TG4RunConfiguration & right) private
Not implemented.
Member Data Documentation
TString TG4RunConfiguration::fUserGeometry protected
way of building geometry
Definition at line 115 of file TG4RunConfiguration.h.
Referenced by CreateDetectorConstruction(), and GetUserGeometry().
TString TG4RunConfiguration::fPhysicsListSelection protected
physics list selection
Definition at line 116 of file TG4RunConfiguration.h.
Referenced by CreatePhysicsList(), and GetPhysicsListSelection().
TString TG4RunConfiguration::fSpecialProcessSelection protected
special process selection
Definition at line 117 of file TG4RunConfiguration.h.
Referenced by CreatePhysicsList(), and TG4RunConfiguration().
Bool_t TG4RunConfiguration::fSpecialStacking protected
option for special stacking
Definition at line 118 of file TG4RunConfiguration.h.
Referenced by CreateStackingAction(), and IsSpecialStacking().
Bool_t TG4RunConfiguration::fMTApplication protected
option for MT mode if available
Definition at line 119 of file TG4RunConfiguration.h.
Referenced by IsMTApplication(), and SetMTApplication().
Bool_t TG4RunConfiguration::fSpecialControls protected
option for special controls
Definition at line 120 of file TG4RunConfiguration.h.
Referenced by IsSpecialControls(), and TG4RunConfiguration().
Bool_t TG4RunConfiguration::fSpecialCuts protected
option for special cuts
Definition at line 121 of file TG4RunConfiguration.h.
Referenced by IsSpecialCuts(), and TG4RunConfiguration().
G4UImessenger* TG4RunConfiguration::fAGDDMessenger protected
XML messenger.
Definition at line 122 of file TG4RunConfiguration.h.
Referenced by TG4RunConfiguration(), and ~TG4RunConfiguration().
G4UImessenger* TG4RunConfiguration::fGDMLMessenger protected
XML messenger.
Definition at line 123 of file TG4RunConfiguration.h.
Referenced by TG4RunConfiguration(), and ~TG4RunConfiguration().
std::map<TString, Double_t> TG4RunConfiguration::fParameters protected
The map of special parameters which need to be set before creating TGeant4 Actually used for monopole properties: monopoleMass, monopoleElCharge, monopoleMagCharge
Definition at line 128 of file TG4RunConfiguration.h.
Referenced by CreatePhysicsList(), and SetParameter().
The documentation for this class was generated from the following files:
source/run/include/TG4RunConfiguration.h
source/run/src/TG4RunConfiguration.cxx